var modelSelect = [
    // default
    {make: "-----", code: "-----", display: "-----"},

    // Acura
    {make: "ACURA", code: "ACUCL", display: "CL"},
    {make: "ACURA", code: "ILX", display: "ILX"},
    {make: "ACURA", code: "INTEG", display: "Integra"},
    {make: "ACURA", code: "LEGEND", display: "Legend"},
    {make: "ACURA", code: "MDX", display: "MDX"},
    {make: "ACURA", code: "NSX", display: "NSX"},
    {make: "ACURA", code: "RDX", display: "RDX"},
    {make: "ACURA", code: "RL", display: "RL"},
    {make: "ACURA", code: "RLX", display: "RLX"},
    {make: "ACURA", code: "RSX", display: "RSX"},
    {make: "ACURA", code: "SLX", display: "SLX"},
    {make: "ACURA", code: "TL", display: "TL"},
    {make: "ACURA", code: "ACUTLX", display: "TLX"},
    {make: "ACURA", code: "TSX", display: "TSX"},
    {make: "ACURA", code: "VIGOR", display: "Vigor"},
    {make: "ACURA", code: "ZDX", display: "ZDX"},
    {make: "ACURA", code: "ACUOTH", display: "Other ACURA Models"},

    // Alfa Romeo
    {make: "ALFA", code: "ALFA164", display: "164"},
    {make: "ALFA", code: "ALFA4C", display: "4C"},
    {make: "ALFA", code: "ALFA8C", display: "8C Competizione"},
    {make: "ALFA", code: "ALFAGT", display: "GTV-6"},
    {make: "ALFA", code: "MIL", display: "Milano"},
    {make: "ALFA", code: "SPID", display: "Spider"},
    {make: "ALFA", code: "ALFAOTH", display: "Other Alfa Romeo Models"},

    // AMC
    {make: "AMC", code: "AMCALLIAN", display: "Alliance"},
    {make: "AMC", code: "CON", display: "Concord"},
    {make: "AMC", code: "EAGLE", display: "Eagle"},
    {make: "AMC", code: "AMCENC", display: "Encore"},
    {make: "AMC", code: "AMCSPIRIT", display: "Spirit"},
    {make: "AMC", code: "AMCOTH", display: "Other AMC Models"},

    // Aston Martin
    {make: "ASTON", code: "DB7", display: "DB7"},
    {make: "ASTON", code: "DB9", display: "DB9"},
    {make: "ASTON", code: "DBS", display: "DBS"},
    {make: "ASTON", code: "LAGONDA", display: "Lagonda"},
    {make: "ASTON", code: "RAPIDE", display: "Rapide"},
    {make: "ASTON", code: "ASTRAPIDES", display: "Rapide S"},
    {make: "ASTON", code: "V12VANT", display: "V12 Vantage"},
    {make: "ASTON", code: "VANTAGE", display: "V8 Vantage"},
    {make: "ASTON", code: "VANQUISH", display: "Vanquish"},
    {make: "ASTON", code: "VIRAGE", display: "Virage"},
    {make: "ASTON", code: "ASTOTH", display: "Other Aston Martin Models"},

    // Audi
    {make: "AUDI", code: "AUDI100", display: "100"},
    {make: "AUDI", code: "AUDI200", display: "200"},
    {make: "AUDI", code: "4000", display: "4000"},
    {make: "AUDI", code: "5000", display: "5000"},
    {make: "AUDI", code: "80", display: "80"},
    {make: "AUDI", code: "90", display: "90"},
    {make: "AUDI", code: "A3", display: "A3"},
    {make: "AUDI", code: "A4", display: "A4"},
    {make: "AUDI", code: "A5", display: "A5"},
    {make: "AUDI", code: "A6", display: "A6"},
    {make: "AUDI", code: "A7", display: "A7"},
    {make: "AUDI", code: "A8", display: "A8"},
    {make: "AUDI", code: "ALLRDQUA", display: "allroad"},
    {make: "AUDI", code: "AUDICABRI", display: "Cabriolet"},
    {make: "AUDI", code: "AUDICOUPE", display: "Coupe"},
    {make: "AUDI", code: "Q3", display: "Q3"},
    {make: "AUDI", code: "Q5", display: "Q5"},
    {make: "AUDI", code: "Q7", display: "Q7"},
    {make: "AUDI", code: "QUATTR", display: "Quattro"},
    {make: "AUDI", code: "R8", display: "R8"},
    {make: "AUDI", code: "RS4", display: "RS 4"},
    {make: "AUDI", code: "RS5", display: "RS 5"},
    {make: "AUDI", code: "RS6", display: "RS 6"},
    {make: "AUDI", code: "AUDIRS7", display: "RS 7"},
    {make: "AUDI", code: "AUDS3", display: "S3"},
    {make: "AUDI", code: "S4", display: "S4"},
    {make: "AUDI", code: "S5", display: "S5"},
    {make: "AUDI", code: "S6", display: "S6"},
    {make: "AUDI", code: "S7", display: "S7"},
    {make: "AUDI", code: "S8", display: "S8"},
    {make: "AUDI", code: "AUDISQ5", display: "SQ5"},
    {make: "AUDI", code: "TT", display: "TT"},
    {make: "AUDI", code: "TTRS", display: "TT RS"},
    {make: "AUDI", code: "TTS", display: "TTS"},
    {make: "AUDI", code: "V8", display: "V8 Quattro"},
    {make: "AUDI", code: "AUDOTH", display: "Other Audi Models"},

    // Bentley
    {make: "BENTL", code: "ARNAGE", display: "Arnage"},
    {make: "BENTL", code: "AZURE", display: "Azure"},
    {make: "BENTL", code: "BROOKLANDS", display: "Brooklands"},
    {make: "BENTL", code: "BENCONT", display: "Continental"},
    {make: "BENTL", code: "BENEIGHT", display: "Eight"},
    {make: "BENTL", code: "BENFLYSPUR", display: "Flying Spur"},
    {make: "BENTL", code: "BENMUL", display: "Mulsanne"},
    {make: "BENTL", code: "BENTURBO", display: "Turbo R"},
    {make: "BENTL", code: "BENOTH", display: "Other Bentley Models"},

    // BMW,
    {make: "BMW", code: "1_SERIES", display: "1 Series (3)"},
    {make: "BMW", code: "128I", display: " - 128i"},
    {make: "BMW", code: "135I", display: " - 135i"},
    {make: "BMW", code: "135IS", display: " - 135is"},
    {make: "BMW", code: "2_SERIES", display: "2 Series (4)"},
    {make: "BMW", code: "BMW228I", display: " - 228i"},
    {make: "BMW", code: "BMW228IXD", display: " - 228i xDrive"},
    {make: "BMW", code: "BMWM235I", display: " - M235i"},
    {make: "BMW", code: "BMWM235IXD", display: " - M235i xDrive"},
    {make: "BMW", code: "3_SERIES", display: "3 Series (36)"},
    {make: "BMW", code: "318I", display: " - 318i"},
    {make: "BMW", code: "318IS", display: " - 318iS"},
    {make: "BMW", code: "318TI", display: " - 318ti"},
    {make: "BMW", code: "320I", display: " - 320i"},
    {make: "BMW", code: "320IXD", display: " - 320i xDrive"},
    {make: "BMW", code: "323CI", display: " - 323ci"},
    {make: "BMW", code: "323I", display: " - 323i"},
    {make: "BMW", code: "323IS", display: " - 323is"},
    {make: "BMW", code: "BMW325", display: " - 325"},
    {make: "BMW", code: "325CI", display: " - 325Ci"},
    {make: "BMW", code: "325E", display: " - 325e"},
    {make: "BMW", code: "325ES", display: " - 325es"},
    {make: "BMW", code: "325I", display: " - 325i"},
    {make: "BMW", code: "325IX", display: " - 325iX"},
    {make: "BMW", code: "325IS", display: " - 325is"},
    {make: "BMW", code: "325XI", display: " - 325xi"},
    {make: "BMW", code: "328CI", display: " - 328Ci"},
    {make: "BMW", code: "BMW328D", display: " - 328d"},
    {make: "BMW", code: "BMW328DXD", display: " - 328d xDrive"},
    {make: "BMW", code: "328I", display: " - 328i"},
    {make: "BMW", code: "BMW328GTXD", display: " - 328i Gran Turismo xDrive"},
    {make: "BMW", code: "328IXD", display: " - 328i xDrive"},
    {make: "BMW", code: "328IS", display: " - 328iS"},
    {make: "BMW", code: "328XI", display: " - 328xi"},
    {make: "BMW", code: "330CI", display: " - 330Ci"},
    {make: "BMW", code: "330I", display: " - 330i"},
    {make: "BMW", code: "330XI", display: " - 330xi"},
    {make: "BMW", code: "335D", display: " - 335d"},
    {make: "BMW", code: "335I", display: " - 335i"},
    {make: "BMW", code: "BMW335GTXD", display: " - 335i Gran Turismo xDrive"},
    {make: "BMW", code: "335IXD", display: " - 335i xDrive"},
    {make: "BMW", code: "335IS", display: " - 335is"},
    {make: "BMW", code: "335XI", display: " - 335xi"},
    {make: "BMW", code: "BMW340I", display: " - 340i"},
    {make: "BMW", code: "BMW340IXD", display: " - 340i xDrive"},
    {make: "BMW", code: "ACTIVE3", display: " - ActiveHybrid 3"},
    {make: "BMW", code: "4_SERIES", display: "4 Series (8)"},
    {make: "BMW", code: "BMW428I", display: " - 428i"},
    {make: "BMW", code: "BMW428GC", display: " - 428i Gran Coupe"},
    {make: "BMW", code: "BMW428GCXD", display: " - 428i Gran Coupe xDrive"},
    {make: "BMW", code: "BMW428IXD", display: " - 428i xDrive"},
    {make: "BMW", code: "BMW435I", display: " - 435i"},
    {make: "BMW", code: "BMW435GC", display: " - 435i Gran Coupe"},
    {make: "BMW", code: "BMW435GCXD", display: " - 435i Gran Coupe xDrive"},
    {make: "BMW", code: "BMW435IXD", display: " - 435i xDrive"},
    {make: "BMW", code: "5_SERIES", display: "5 Series (24)"},
    {make: "BMW", code: "524TD", display: " - 524td"},
    {make: "BMW", code: "525I", display: " - 525i"},
    {make: "BMW", code: "525XI", display: " - 525xi"},
    {make: "BMW", code: "528E", display: " - 528e"},
    {make: "BMW", code: "528I", display: " - 528i"},
    {make: "BMW", code: "528IXD", display: " - 528i xDrive"},
    {make: "BMW", code: "528XI", display: " - 528xi"},
    {make: "BMW", code: "530I", display: " - 530i"},
    {make: "BMW", code: "530XI", display: " - 530xi"},
    {make: "BMW", code: "533I", display: " - 533i"},
    {make: "BMW", code: "BMW535D", display: " - 535d"},
    {make: "BMW", code: "BMW535DXD", display: " - 535d xDrive"},
    {make: "BMW", code: "535I", display: " - 535i"},
    {make: "BMW", code: "535IGT", display: " - 535i Gran Turismo"},
    {make: "BMW", code: "535IGTXD", display: " - 535i Gran Turismo xDrive"},
    {make: "BMW", code: "535IXD", display: " - 535i xDrive"},
    {make: "BMW", code: "535XI", display: " - 535xi"},
    {make: "BMW", code: "540I", display: " - 540i"},
    {make: "BMW", code: "545I", display: " - 545i"},
    {make: "BMW", code: "550I", display: " - 550i"},
    {make: "BMW", code: "550IGT", display: " - 550i Gran Turismo"},
    {make: "BMW", code: "550IGTXD", display: " - 550i Gran Turismo xDrive"},
    {make: "BMW", code: "550IXD", display: " - 550i xDrive"},
    {make: "BMW", code: "ACTIVE5", display: " - ActiveHybrid 5"},
    {make: "BMW", code: "6_SERIES", display: "6 Series (13)"},
    {make: "BMW", code: "633CSI", display: " - 633CSi"},
    {make: "BMW", code: "635CSI", display: " - 635CSi"},
    {make: "BMW", code: "640I", display: " - 640i"},
    {make: "BMW", code: "640IGC", display: " - 640i Gran Coupe"},
    {make: "BMW", code: "BMW640GCXD", display: " - 640i Gran Coupe xDrive"},
    {make: "BMW", code: "BMW640IXD", display: " - 640i xDrive"},
    {make: "BMW", code: "645CI", display: " - 645Ci"},
    {make: "BMW", code: "650I", display: " - 650i"},
    {make: "BMW", code: "650IGC", display: " - 650i Gran Coupe"},
    {make: "BMW", code: "650IGCXD", display: " - 650i Gran Coupe xDrive"},
    {make: "BMW", code: "650IXD", display: " - 650i xDrive"},
    {make: "BMW", code: "BMWB6XDGC", display: " - ALPINA B6 xDrive Gran Coupe"},
    {make: "BMW", code: "L6", display: " - L6"},
    {make: "BMW", code: "7_SERIES", display: "7 Series (21)"},
    {make: "BMW", code: "733I", display: " - 733i"},
    {make: "BMW", code: "735I", display: " - 735i"},
    {make: "BMW", code: "735IL", display: " - 735iL"},
    {make: "BMW", code: "BMW740LDXD", display: " - 740Ld xDrive"},
    {make: "BMW", code: "740LI", display: " - 740Li"},
    {make: "BMW", code: "740LIXD", display: " - 740Li xDrive"},
    {make: "BMW", code: "740I", display: " - 740i"},
    {make: "BMW", code: "740IL", display: " - 740iL"},
    {make: "BMW", code: "745LI", display: " - 745Li"},
    {make: "BMW", code: "745I", display: " - 745i"},
    {make: "BMW", code: "750LI", display: " - 750Li"},
    {make: "BMW", code: "750LIXD", display: " - 750Li xDrive"},
    {make: "BMW", code: "750I", display: " - 750i"},
    {make: "BMW", code: "750IXD", display: " - 750i xDrive"},
    {make: "BMW", code: "750IL", display: " - 750iL"},
    {make: "BMW", code: "760LI", display: " - 760Li"},
    {make: "BMW", code: "760I", display: " - 760i"},
    {make: "BMW", code: "ALPINAB7", display: " - ALPINA B7"},
    {make: "BMW", code: "ALPINAB7XD", display: " - ALPINA B7 xDrive"},
    {make: "BMW", code: "ACTIVE7", display: " - ActiveHybrid 7"},
    {make: "BMW", code: "L7", display: " - L7"},
    {make: "BMW", code: "8_SERIES", display: "8 Series (4)"},
    {make: "BMW", code: "840CI", display: " - 840Ci"},
    {make: "BMW", code: "850CSI", display: " - 850CSi"},
    {make: "BMW", code: "850CI", display: " - 850Ci"},
    {make: "BMW", code: "850I", display: " - 850i"},
    {make: "BMW", code: "ACTIVEX6", display: "ActiveHybrid X6"},
    {make: "BMW", code: "BMWI3", display: "i3"},
    {make: "BMW", code: "BMWI8", display: "i8"},
    {make: "BMW", code: "BMWMCOUPE", display: "M Coupe"},
    {make: "BMW", code: "BMWROAD", display: "M Roadster"},
    {make: "BMW", code: "M3", display: "M3"},
    {make: "BMW", code: "BMWM4", display: "M4"},
    {make: "BMW", code: "M5", display: "M5"},
    {make: "BMW", code: "M6", display: "M6"},
    {make: "BMW", code: "BMWM6GC", display: "M6 Gran Coupe"},
    {make: "BMW", code: "X1", display: "X1"},
    {make: "BMW", code: "X3", display: "X3"},
    {make: "BMW", code: "BMWX4", display: "X4"},
    {make: "BMW", code: "X5", display: "X5"},
    {make: "BMW", code: "X5M", display: "X5 M"},
    {make: "BMW", code: "X6", display: "X6"},
    {make: "BMW", code: "X6M", display: "X6 M"},
    {make: "BMW", code: "Z3", display: "Z3"},
    {make: "BMW", code: "Z4", display: "Z4"},
    {make: "BMW", code: "Z8", display: "Z8"},
    {make: "BMW", code: "BMWOTH", display: "Other BMW Models"},

    // Buick
    {make: "BUICK", code: "BUICASCADA", display: "Cascada"},
    {make: "BUICK", code: "CENT", display: "Century"},
    {make: "BUICK", code: "ELEC", display: "Electra"},
    {make: "BUICK", code: "ENCLAVE", display: "Enclave"},
    {make: "BUICK", code: "BUIENC", display: "Encore"},
    {make: "BUICK", code: "BUIENVISI", display: "Envision"},
    {make: "BUICK", code: "LACROSSE", display: "LaCrosse"},
    {make: "BUICK", code: "LESA", display: "Le Sabre"},
    {make: "BUICK", code: "LUCERNE", display: "Lucerne"},
    {make: "BUICK", code: "PARK", display: "Park Avenue"},
    {make: "BUICK", code: "RAINIER", display: "Rainier"},
    {make: "BUICK", code: "REATTA", display: "Reatta"},
    {make: "BUICK", code: "REG", display: "Regal"},
    {make: "BUICK", code: "RENDEZVOUS", display: "Rendezvous"},
    {make: "BUICK", code: "RIV", display: "Riviera"},
    {make: "BUICK", code: "BUICKROAD", display: "Roadmaster"},
    {make: "BUICK", code: "SKYH", display: "Skyhawk"},
    {make: "BUICK", code: "SKYL", display: "Skylark"},
    {make: "BUICK", code: "SOMER", display: "Somerset"},
    {make: "BUICK", code: "TERRAZA", display: "Terraza"},
    {make: "BUICK", code: "BUVERANO", display: "Verano"},
    {make: "BUICK", code: "BUOTH", display: "Other Buick Models"},

    // Cadillac
    {make: "CAD", code: "ALLANT", display: "Allante"},
    {make: "CAD", code: "ATS", display: "ATS"},
    {make: "CAD", code: "BROUGH", display: "Brougham"},
    {make: "CAD", code: "CATERA", display: "Catera"},
    {make: "CAD", code: "CIMA", display: "Cimarron"},
    {make: "CAD", code: "CADCT6", display: "CT6"},
    {make: "CAD", code: "CTS", display: "CTS"},
    {make: "CAD", code: "DEV", display: "De Ville"},
    {make: "CAD", code: "DTS", display: "DTS"},
    {make: "CAD", code: "ELDO", display: "Eldorado"},
    {make: "CAD", code: "CADELR", display: "ELR"},
    {make: "CAD", code: "ESCALA", display: "Escalade"},
    {make: "CAD", code: "ESCALAESV", display: "Escalade ESV"},
    {make: "CAD", code: "EXT", display: "Escalade EXT"},
    {make: "CAD", code: "FLEE", display: "Fleetwood"},
    {make: "CAD", code: "SEV", display: "Seville"},
    {make: "CAD", code: "SRX", display: "SRX"},
    {make: "CAD", code: "STS", display: "STS"},
    {make: "CAD", code: "XLR", display: "XLR"},
    {make: "CAD", code: "XTS", display: "XTS"},
    {make: "CAD", code: "CADOTH", display: "Other Cadillac Models"},

    // Chevy
    {make: "CHEV", code: "ASTRO", display: "Astro"},
    {make: "CHEV", code: "AVALNCH", display: "Avalanche"},
    {make: "CHEV", code: "AVEO", display: "Aveo"},
    {make: "CHEV", code: "AVEO5", display: "Aveo5"},
    {make: "CHEV", code: "BERETT", display: "Beretta"},
    {make: "CHEV", code: "BLAZER", display: "Blazer"},
    {make: "CHEV", code: "CAM", display: "Camaro"},
    {make: "CHEV", code: "CAP", display: "Caprice"},
    {make: "CHEV", code: "CHECAPS", display: "Captiva Sport"},
    {make: "CHEV", code: "CAV", display: "Cavalier"},
    {make: "CHEV", code: "CELE", display: "Celebrity"},
    {make: "CHEV", code: "CHEVETTE", display: "Chevette"},
    {make: "CHEV", code: "CITATION", display: "Citation"},
    {make: "CHEV", code: "CHECITYEXP", display: "City Express"},
    {make: "CHEV", code: "COBALT", display: "Cobalt"},
    {make: "CHEV", code: "COLORADO", display: "Colorado"},
    {make: "CHEV", code: "CORSI", display: "Corsica"},
    {make: "CHEV", code: "CORV", display: "Corvette"},
    {make: "CHEV", code: "CRUZE", display: "Cruze"},
    {make: "CHEV", code: "ELCAM", display: "El Camino"},
    {make: "CHEV", code: "EQUINOX", display: "Equinox"},
    {make: "CHEV", code: "CHEXP1500", display: "Express 1500"},
    {make: "CHEV", code: "CHEXP2500", display: "Express 2500"},
    {make: "CHEV", code: "CHEXP3500", display: "Express 3500"},
    {make: "CHEV", code: "CHEXP4500", display: "Express 4500"},
    {make: "CHEV", code: "CHEG10", display: "G10"},
    {make: "CHEV", code: "CHEG20", display: "G20"},
    {make: "CHEV", code: "CHEG30", display: "G30"},
    {make: "CHEV", code: "HHR", display: "HHR"},
    {make: "CHEV", code: "CHEVIMP", display: "Impala"},
    {make: "CHEV", code: "KODC4500", display: "Kodiak C4500"},
    {make: "CHEV", code: "LUMINA", display: "Lumina"},
    {make: "CHEV", code: "LAPV", display: "Lumina APV"},
    {make: "CHEV", code: "LUV", display: "LUV"},
    {make: "CHEV", code: "MALI", display: "Malibu"},
    {make: "CHEV", code: "CHVMETR", display: "Metro"},
    {make: "CHEV", code: "CHEVMONT", display: "Monte Carlo"},
    {make: "CHEV", code: "NOVA", display: "Nova"},
    {make: "CHEV", code: "CHEVPRIZM", display: "Prizm"},
    {make: "CHEV", code: "CHVST", display: "S10 Blazer"},
    {make: "CHEV", code: "S10PICKUP", display: "S10 Pickup"},
    {make: "CHEV", code: "CHEV150", display: "Silverado and other C/K1500"},
    {make: "CHEV", code: "CHEVC25", display: "Silverado and other C/K2500"},
    {make: "CHEV", code: "CH3500PU", display: "Silverado and other C/K3500"},
    {make: "CHEV", code: "SONIC", display: "Sonic"},
    {make: "CHEV", code: "SPARK", display: "Spark"},
    {make: "CHEV", code: "CHEVSPEC", display: "Spectrum"},
    {make: "CHEV", code: "CHSPRINT", display: "Sprint"},
    {make: "CHEV", code: "CHEVSS", display: "SS"},
    {make: "CHEV", code: "SSR", display: "SSR"},
    {make: "CHEV", code: "CHEVSUB", display: "Suburban"},
    {make: "CHEV", code: "TAHOE", display: "Tahoe"},
    {make: "CHEV", code: "TRACKE", display: "Tracker"},
    {make: "CHEV", code: "TRAILBLZ", display: "TrailBlazer"},
    {make: "CHEV", code: "TRAILBZEXT", display: "TrailBlazer EXT"},
    {make: "CHEV", code: "TRAVERSE", display: "Traverse"},
    {make: "CHEV", code: "CHETRAX", display: "Trax"},
    {make: "CHEV", code: "UPLANDER", display: "Uplander"},
    {make: "CHEV", code: "VENTUR", display: "Venture"},
    {make: "CHEV", code: "VOLT", display: "Volt"},
    {make: "CHEV", code: "CHEOTH", display: "Other Chevrolet Models"},

    // Chrysler
    {make: "CHRY", code: "CHRYS200", display: "200"},
    {make: "CHRY", code: "300", display: "300"},
    {make: "CHRY", code: "CHRY300", display: "300M"},
    {make: "CHRY", code: "ASPEN", display: "Aspen"},
    {make: "CHRY", code: "CIRRUS", display: "Cirrus"},
    {make: "CHRY", code: "CONC", display: "Concorde"},
    {make: "CHRY", code: "CHRYCONQ", display: "Conquest"},
    {make: "CHRY", code: "CORDOBA", display: "Cordoba"},
    {make: "CHRY", code: "CROSSFIRE", display: "Crossfire"},
    {make: "CHRY", code: "ECLASS", display: "E Class"},
    {make: "CHRY", code: "FIFTH", display: "Fifth Avenue"},
    {make: "CHRY", code: "CHRYGRANDV", display: "Grand Voyager"},
    {make: "CHRY", code: "IMPE", display: "Imperial"},
    {make: "CHRY", code: "INTREPID", display: "Intrepid"},
    {make: "CHRY", code: "CHRYLAS", display: "Laser"},
    {make: "CHRY", code: "LEBA", display: "LeBaron"},
    {make: "CHRY", code: "CHRYLEBGTS", display: "LeBaron GTS"},
    {make: "CHRY", code: "LHS", display: "LHS"},
    {make: "CHRY", code: "NY", display: "New Yorker"},
    {make: "CHRY", code: "NEWPORT", display: "Newport"},
    {make: "CHRY", code: "PACIFICA", display: "Pacifica"},
    {make: "CHRY", code: "CHPROWLE", display: "Prowler"},
    {make: "CHRY", code: "PTCRUIS", display: "PT Cruiser"},
    {make: "CHRY", code: "CHRYSEB", display: "Sebring"},
    {make: "CHRY", code: "CHRYTC", display: "TC by Maserati"},
    {make: "CHRY", code: "TANDC", display: "Town & Country"},
    {make: "CHRY", code: "VOYAGER", display: "Voyager"},
    {make: "CHRY", code: "CHOTH", display: "Other Chrysler Models"},

    // Daewoo
    {make: "DAEW", code: "LANOS", display: "Lanos"},
    {make: "DAEW", code: "LEGANZA", display: "Leganza"},
    {make: "DAEW", code: "NUBIRA", display: "Nubira"},
    {make: "DAEW", code: "DAEOTH", display: "Other Daewoo Models"},

    // Datsun
    {make: "DATSUN", code: "DAT200SX", display: "200SX"},
    {make: "DATSUN", code: "DAT210", display: "210"},
    {make: "DATSUN", code: "280Z", display: "280ZX"},
    {make: "DATSUN", code: "300ZX", display: "300ZX"},
    {make: "DATSUN", code: "310", display: "310"},
    {make: "DATSUN", code: "510", display: "510"},
    {make: "DATSUN", code: "720", display: "720"},
    {make: "DATSUN", code: "810", display: "810"},
    {make: "DATSUN", code: "DATMAX", display: "Maxima"},
    {make: "DATSUN", code: "DATPU", display: "Pickup"},
    {make: "DATSUN", code: "PUL", display: "Pulsar"},
    {make: "DATSUN", code: "DATSENT", display: "Sentra"},
    {make: "DATSUN", code: "STAN", display: "Stanza"},
    {make: "DATSUN", code: "DATOTH", display: "Other Datsun Models"},

    // DeLorean
    {make: "DELOREAN", code: "DMC12", display: "DMC-12"},

    // Dodge
    {make: "DODGE", code: "400", display: "400"},
    {make: "DODGE", code: "DOD600", display: "600"},
    {make: "DODGE", code: "ARI", display: "Aries"},
    {make: "DODGE", code: "AVENGR", display: "Avenger"},
    {make: "DODGE", code: "B150", display: "B150"},
    {make: "DODGE", code: "B1500", display: "B1500"},
    {make: "DODGE", code: "B250", display: "B250"},
    {make: "DODGE", code: "B2500", display: "B2500"},
    {make: "DODGE", code: "B350", display: "B350"},
    {make: "DODGE", code: "B3500", display: "B3500"},
    {make: "DODGE", code: "CALIBER", display: "Caliber"},
    {make: "DODGE", code: "DODCARA", display: "Caravan"},
    {make: "DODGE", code: "CHALLENGER", display: "Challenger"},
    {make: "DODGE", code: "DODCHAR", display: "Charger"},
    {make: "DODGE", code: "DODCOLT", display: "Colt"},
    {make: "DODGE", code: "DODCONQ", display: "Conquest"},
    {make: "DODGE", code: "DODDW", display: "D/W Truck"},
    {make: "DODGE", code: "DAKOTA", display: "Dakota"},
    {make: "DODGE", code: "DODDART", display: "Dart"},
    {make: "DODGE", code: "DAY", display: "Daytona"},
    {make: "DODGE", code: "DIPLOMA", display: "Diplomat"},
    {make: "DODGE", code: "DURANG", display: "Durango"},
    {make: "DODGE", code: "DODDYNA", display: "Dynasty"},
    {make: "DODGE", code: "GRANDCARAV", display: "Grand Caravan"},
    {make: "DODGE", code: "INTRE", display: "Intrepid"},
    {make: "DODGE", code: "JOURNEY", display: "Journey"},
    {make: "DODGE", code: "LANCERDODG", display: "Lancer"},
    {make: "DODGE", code: "MAGNUM", display: "Magnum"},
    {make: "DODGE", code: "MIRADA", display: "Mirada"},
    {make: "DODGE", code: "MONACO", display: "Monaco"},
    {make: "DODGE", code: "DODNEON", display: "Neon"},
    {make: "DODGE", code: "NITRO", display: "Nitro"},
    {make: "DODGE", code: "OMNI", display: "Omni"},
    {make: "DODGE", code: "RAIDER", display: "Raider"},
    {make: "DODGE", code: "RAM1504WD", display: "Ram 1500 Truck"},
    {make: "DODGE", code: "RAM25002WD", display: "Ram 2500 Truck"},
    {make: "DODGE", code: "RAM3502WD", display: "Ram 3500 Truck"},
    {make: "DODGE", code: "RAM4500", display: "Ram 4500 Truck"},
    {make: "DODGE", code: "DODD50", display: "Ram 50 Truck"},
    {make: "DODGE", code: "RAM5500", display: "Ram 5500 Truck"},
    {make: "DODGE", code: "RAMSRT10", display: "Ram SRT-10"},
    {make: "DODGE", code: "RAMCGR", display: "Ramcharger"},
    {make: "DODGE", code: "RAMPAGE", display: "Rampage"},
    {make: "DODGE", code: "DODSHAD", display: "Shadow"},
    {make: "DODGE", code: "DODSPIR", display: "Spirit"},
    {make: "DODGE", code: "SPRINTER", display: "Sprinter"},
    {make: "DODGE", code: "SRT4", display: "SRT-4"},
    {make: "DODGE", code: "STREGIS", display: "St. Regis"},
    {make: "DODGE", code: "STEAL", display: "Stealth"},
    {make: "DODGE", code: "STRATU", display: "Stratus"},
    {make: "DODGE", code: "VIPER", display: "Viper"},
    {make: "DODGE", code: "DOOTH", display: "Other Dodge Models"},

    // Eagle
    {make: "EAGLE", code: "EAGLEMED", display: "Medallion"},
    {make: "EAGLE", code: "EAGLEPREM", display: "Premier"},
    {make: "EAGLE", code: "SUMMIT", display: "Summit"},
    {make: "EAGLE", code: "TALON", display: "Talon"},
    {make: "EAGLE", code: "VISION", display: "Vision"},
    {make: "EAGLE", code: "EAGOTH", display: "Other Eagle Models"},

    // Ferrari
    {make: "FER", code: "308", display: "308"},
    {make: "FER", code: "328", display: "328"},
    {make: "FER", code: "348", display: "348"},
    {make: "FER", code: "360", display: "360"},
    {make: "FER", code: "456GT", display: "456 GT"},
    {make: "FER", code: "456MGT", display: "456M GT"},
    {make: "FER", code: "458ITALIA", display: "458 Italia"},
    {make: "FER", code: "512M", display: "512M"},
    {make: "FER", code: "512TR", display: "512TR"},
    {make: "FER", code: "550M", display: "550 Maranello"},
    {make: "FER", code: "575M", display: "575M Maranello"},
    {make: "FER", code: "599GTB", display: "599 GTB Fiorano"},
    {make: "FER", code: "599GTO", display: "599 GTO"},
    {make: "FER", code: "612SCAGLIE", display: "612 Scaglietti"},
    {make: "FER", code: "FERCALIF", display: "California"},
    {make: "FER", code: "ENZO", display: "Enzo"},
    {make: "FER", code: "FERF12BERL", display: "F12 Berlinetta"},
    {make: "FER", code: "F355", display: "F355"},
    {make: "FER", code: "F40", display: "F40"},
    {make: "FER", code: "F430", display: "F430"},
    {make: "FER", code: "F50", display: "F50"},
    {make: "FER", code: "FERFF", display: "FF"},
    {make: "FER", code: "MOND", display: "Mondial"},
    {make: "FER", code: "TEST", display: "Testarossa"},
    {make: "FER", code: "FEROTH", display: "Other Ferrari Models"},

    // FIAT
    {make: "FIAT", code: "2000", display: "2000 Spider"},
    {make: "FIAT", code: "FIAT500", display: "500"},
    {make: "FIAT", code: "FIAT500L", display: "500L"},
    {make: "FIAT", code: "FIAT500X", display: "500X"},
    {make: "FIAT", code: "BERTON", display: "Bertone X1/9"},
    {make: "FIAT", code: "BRAVA", display: "Brava"},
    {make: "FIAT", code: "PININ", display: "Pininfarina Spider"},
    {make: "FIAT", code: "STRADA", display: "Strada"},
    {make: "FIAT", code: "FIATX19", display: "X1/9"},
    {make: "FIAT", code: "FIAOTH", display: "Other Fiat Models"},

    // Fisker
    {make: "FISK", code: "KARMA", display: "Karma"},

    // Ford
    {make: "FORD", code: "AERO", display: "Aerostar"},
    {make: "FORD", code: "ASPIRE", display: "Aspire"},
    {make: "FORD", code: "BRON", display: "Bronco"},
    {make: "FORD", code: "B2", display: "Bronco II"},
    {make: "FORD", code: "FOCMAX", display: "C-MAX"},
    {make: "FORD", code: "CONTOUR", display: "Contour"},
    {make: "FORD", code: "COURIER", display: "Courier"},
    {make: "FORD", code: "CROWNVIC", display: "Crown Victoria"},
    {make: "FORD", code: "E100ECON", display: "E-100"},
    {make: "FORD", code: "E150ECON", display: "E-150 and Econoline 150"},
    {make: "FORD", code: "E250ECON", display: "E-250 and Econoline 250"},
    {make: "FORD", code: "E350ECON", display: "E-350 and Econoline 350"},
    {make: "FORD", code: "EDGE", display: "Edge"},
    {make: "FORD", code: "ESCAPE", display: "Escape"},
    {make: "FORD", code: "ESCO", display: "Escort"},
    {make: "FORD", code: "EXCURSION", display: "Excursion"},
    {make: "FORD", code: "EXP", display: "EXP"},
    {make: "FORD", code: "EXPEDI", display: "Expedition"},
    {make: "FORD", code: "EXPEDIEL", display: "Expedition EL"},
    {make: "FORD", code: "EXPLOR", display: "Explorer"},
    {make: "FORD", code: "SPORTTRAC", display: "Explorer Sport Trac"},
    {make: "FORD", code: "F100", display: "F100"},
    {make: "FORD", code: "F150PICKUP", display: "F150"},
    {make: "FORD", code: "F250", display: "F250"},
    {make: "FORD", code: "F350", display: "F350"},
    {make: "FORD", code: "F450", display: "F450"},
    {make: "FORD", code: "FAIRM", display: "Fairmont"},
    {make: "FORD", code: "FESTIV", display: "Festiva"},
    {make: "FORD", code: "FIESTA", display: "Fiesta"},
    {make: "FORD", code: "FIVEHUNDRE", display: "Five Hundred"},
    {make: "FORD", code: "FLEX", display: "Flex"},
    {make: "FORD", code: "FOCUS", display: "Focus"},
    {make: "FORD", code: "FREESTAR", display: "Freestar"},
    {make: "FORD", code: "FREESTYLE", display: "Freestyle"},
    {make: "FORD", code: "FUSION", display: "Fusion"},
    {make: "FORD", code: "GRANADA", display: "Granada"},
    {make: "FORD", code: "GT", display: "GT"},
    {make: "FORD", code: "LTD", display: "LTD"},
    {make: "FORD", code: "MUST", display: "Mustang"},
    {make: "FORD", code: "PROBE", display: "Probe"},
    {make: "FORD", code: "RANGER", display: "Ranger"},
    {make: "FORD", code: "TAURUS", display: "Taurus"},
    {make: "FORD", code: "TAURUSX", display: "Taurus X"},
    {make: "FORD", code: "TEMPO", display: "Tempo"},
    {make: "FORD", code: "TBIRD", display: "Thunderbird"},
    {make: "FORD", code: "FORDTRN150", display: "Transit 150"},
    {make: "FORD", code: "FORDTRN250", display: "Transit 250"},
    {make: "FORD", code: "FORDTRN350", display: "Transit 350"},
    {make: "FORD", code: "TRANSCONN", display: "Transit Connect"},
    {make: "FORD", code: "WINDST", display: "Windstar"},
    {make: "FORD", code: "FORDZX2", display: "ZX2 Escort"},
    {make: "FORD", code: "FOOTH", display: "Other Ford Models"},

    // Freightliner
    {make: "FREIGHT", code: "FRESPRINT", display: "Sprinter"},

    // GEO
    {make: "GEO", code: "GEOMETRO", display: "Metro"},
    {make: "GEO", code: "GEOPRIZM", display: "Prizm"},
    {make: "GEO", code: "SPECT", display: "Spectrum"},
    {make: "GEO", code: "STORM", display: "Storm"},
    {make: "GEO", code: "GEOTRACK", display: "Tracker"},
    {make: "GEO", code: "GEOOTH", display: "Other Geo Models"},

    // GMC
    {make: "GMC", code: "ACADIA", display: "Acadia"},
    {make: "GMC", code: "CABALLERO", display: "Caballero"},
    {make: "GMC", code: "CANYON", display: "Canyon"},
    {make: "GMC", code: "ENVOY", display: "Envoy"},
    {make: "GMC", code: "ENVOYXL", display: "Envoy XL"},
    {make: "GMC", code: "ENVOYXUV", display: "Envoy XUV"},
    {make: "GMC", code: "G1500", display: "G1500"},
    {make: "GMC", code: "G2500", display: "G2500"},
    {make: "GMC", code: "G3500", display: "G3500"},
    {make: "GMC", code: "JIM", display: "Jimmy"},
    {make: "GMC", code: "GMCS15", display: "S15 Jimmy"},
    {make: "GMC", code: "S15", display: "S15 Pickup"},
    {make: "GMC", code: "SAFARIGMC", display: "Safari"},
    {make: "GMC", code: "GMCSAVANA", display: "Savana 1500"},
    {make: "GMC", code: "GMCSAV2500", display: "Savana 2500"},
    {make: "GMC", code: "GMCSAV3500", display: "Savana 3500"},
    {make: "GMC", code: "GMCSAV4500", display: "Savana 4500"},
    {make: "GMC", code: "15SIPU4WD", display: "Sierra C/K1500"},
    {make: "GMC", code: "GMCC25PU", display: "Sierra C/K2500"},
    {make: "GMC", code: "GMC3500PU", display: "Sierra C/K3500"},
    {make: "GMC", code: "SONOMA", display: "Sonoma"},
    {make: "GMC", code: "SUB", display: "Suburban"},
    {make: "GMC", code: "GMCSYCLON", display: "Syclone"},
    {make: "GMC", code: "TERRAIN", display: "Terrain"},
    {make: "GMC", code: "TOPC4500", display: "TopKick C4500"},
    {make: "GMC", code: "TYPH", display: "Typhoon"},
    {make: "GMC", code: "YUKON", display: "Yukon"},
    {make: "GMC", code: "YUKONXL", display: "Yukon XL"},
    {make: "GMC", code: "GMCOTH", display: "Other GMC Models"},

    // Honda
    {make: "HONDA", code: "ACCORD", display: "Accord"},
    {make: "HONDA", code: "CIVIC", display: "Civic"},
    {make: "HONDA", code: "CRV", display: "CR-V"},
    {make: "HONDA", code: "CRZ", display: "CR-Z"},
    {make: "HONDA", code: "CRX", display: "CRX"},
    {make: "HONDA", code: "CROSSTOUR_MODELS", display: "Crosstour Models (2)"},
    {make: "HONDA", code: "CROSSTOUR", display: " - Accord Crosstour"},
    {make: "HONDA", code: "HONCROSS", display: " - Crosstour"},
    {make: "HONDA", code: "HONDELSOL", display: "Del Sol"},
    {make: "HONDA", code: "ELEMENT", display: "Element"},
    {make: "HONDA", code: "FIT", display: "Fit"},
    {make: "HONDA", code: "HONHRV", display: "HR-V"},
    {make: "HONDA", code: "INSIGHT", display: "Insight"},
    {make: "HONDA", code: "ODYSSEY", display: "Odyssey"},
    {make: "HONDA", code: "PASSPO", display: "Passport"},
    {make: "HONDA", code: "PILOT", display: "Pilot"},
    {make: "HONDA", code: "PRE", display: "Prelude"},
    {make: "HONDA", code: "RIDGELINE", display: "Ridgeline"},
    {make: "HONDA", code: "S2000", display: "S2000"},
    {make: "HONDA", code: "HONOTH", display: "Other Honda Models"},

    // Hummer
    {make: "AMGEN", code: "HUMMER", display: "H1"},
    {make: "AMGEN", code: "H2", display: "H2"},
    {make: "AMGEN", code: "H3", display: "H3"},
    {make: "AMGEN", code: "H3T", display: "H3T"},
    {make: "AMGEN", code: "AMGOTH", display: "Other Hummer Models"},

    // Hyundai
    {make: "HYUND", code: "ACCENT", display: "Accent"},
    {make: "HYUND", code: "AZERA", display: "Azera"},
    {make: "HYUND", code: "ELANTR", display: "Elantra"},
    {make: "HYUND", code: "HYUELANCPE", display: "Elantra Coupe"},
    {make: "HYUND", code: "ELANTOUR", display: "Elantra Touring"},
    {make: "HYUND", code: "ENTOURAGE", display: "Entourage"},
    {make: "HYUND", code: "EQUUS", display: "Equus"},
    {make: "HYUND", code: "HYUEXCEL", display: "Excel"},
    {make: "HYUND", code: "GENESIS", display: "Genesis"},
    {make: "HYUND", code: "GENESISCPE", display: "Genesis Coupe"},
    {make: "HYUND", code: "SANTAFE", display: "Santa Fe"},
    {make: "HYUND", code: "SCOUPE", display: "Scoupe"},
    {make: "HYUND", code: "SONATA", display: "Sonata"},
    {make: "HYUND", code: "TIBURO", display: "Tiburon"},
    {make: "HYUND", code: "TUCSON", display: "Tucson"},
    {make: "HYUND", code: "VELOSTER", display: "Veloster"},
    {make: "HYUND", code: "VERACRUZ", display: "Veracruz"},
    {make: "HYUND", code: "XG300", display: "XG300"},
    {make: "HYUND", code: "XG350", display: "XG350"},
    {make: "HYUND", code: "HYUOTH", display: "Other Hyundai Models"},

    // Infiniti
    {make: "INFIN", code: "EX_MODELS", display: "EX Models (2)"},
    {make: "INFIN", code: "EX35", display: " - EX35"},
    {make: "INFIN", code: "EX37", display: " - EX37"},
    {make: "INFIN", code: "FX_MODELS", display: "FX Models (4)"},
    {make: "INFIN", code: "FX35", display: " - FX35"},
    {make: "INFIN", code: "FX37", display: " - FX37"},
    {make: "INFIN", code: "FX45", display: " - FX45"},
    {make: "INFIN", code: "FX50", display: " - FX50"},
    {make: "INFIN", code: "G_MODELS", display: "G Models (4)"},
    {make: "INFIN", code: "G20", display: " - G20"},
    {make: "INFIN", code: "G25", display: " - G25"},
    {make: "INFIN", code: "G35", display: " - G35"},
    {make: "INFIN", code: "G37", display: " - G37"},
    {make: "INFIN", code: "I30", display: "I30"},
    {make: "INFIN", code: "I35", display: "I35"},
    {make: "INFIN", code: "J30", display: "J30"},
    {make: "INFIN", code: "JX35", display: "JX35"},
    {make: "INFIN", code: "M_MODELS", display: "M Models (6)"},
    {make: "INFIN", code: "M30", display: " - M30"},
    {make: "INFIN", code: "M35", display: " - M35"},
    {make: "INFIN", code: "M35HYBRID", display: " - M35h"},
    {make: "INFIN", code: "M37", display: " - M37"},
    {make: "INFIN", code: "M45", display: " - M45"},
    {make: "INFIN", code: "M56", display: " - M56"},
    {make: "INFIN", code: "INFINQ40", display: "Q40"},
    {make: "INFIN", code: "Q45", display: "Q45"},
    {make: "INFIN", code: "INFINQ50", display: "Q50"},
    {make: "INFIN", code: "INFINQ60", display: "Q60"},
    {make: "INFIN", code: "INFINQ70", display: "Q70"},
    {make: "INFIN", code: "QX4", display: "QX4"},
    {make: "INFIN", code: "INFINQX50", display: "QX50"},
    {make: "INFIN", code: "QX56", display: "QX56"},
    {make: "INFIN", code: "INFINQX60", display: "QX60"},
    {make: "INFIN", code: "INFINQX70", display: "QX70"},
    {make: "INFIN", code: "INFINQX80", display: "QX80"},
    {make: "INFIN", code: "INFOTH", display: "Other Infiniti Models"},
    
    // Isuzu
    {make: "ISU", code: "AMIGO", display: "Amigo"},
    {make: "ISU", code: "ASCENDER", display: "Ascender"},
    {make: "ISU", code: "AXIOM", display: "Axiom"},
    {make: "ISU", code: "HOMBRE", display: "Hombre"},
    {make: "ISU", code: "I280", display: "i-280"},
    {make: "ISU", code: "I290", display: "i-290"},
    {make: "ISU", code: "I350", display: "i-350"},
    {make: "ISU", code: "I370", display: "i-370"},
    {make: "ISU", code: "ISUMARK", display: "I-Mark"},
    {make: "ISU", code: "ISUIMP", display: "Impulse"},
    {make: "ISU", code: "OASIS", display: "Oasis"},
    {make: "ISU", code: "ISUPU", display: "Pickup"},
    {make: "ISU", code: "RODEO", display: "Rodeo"},
    {make: "ISU", code: "STYLUS", display: "Stylus"},
    {make: "ISU", code: "TROOP", display: "Trooper"},
    {make: "ISU", code: "TRP2", display: "Trooper II"},
    {make: "ISU", code: "VEHICROSS", display: "VehiCROSS"},
    {make: "ISU", code: "ISUOTH", display: "Other Isuzu Models"},
    
    // Jaguar
    {make: "JAG", code: "JAGFTYPE", display: "F-TYPE"},
    {make: "JAG", code: "STYPE", display: "S-TYPE"},
    {make: "JAG", code: "XTYPE", display: "X-TYPE"},
    {make: "JAG", code: "XF", display: "XF"},
    {make: "JAG", code: "XJ_SERIES", display: "XJ Series (10)"},
    {make: "JAG", code: "XJ", display: " - XJ"},
    {make: "JAG", code: "XJSPORT", display: " - XJ Sport"},
    {make: "JAG", code: "VANDEN", display: " - XJ Vanden Plas"},
    {make: "JAG", code: "JAGXJ12", display: " - XJ12"},
    {make: "JAG", code: "JAGXJ6", display: " - XJ6"},
    {make: "JAG", code: "XJ8", display: " - XJ8"},
    {make: "JAG", code: "XJ8L", display: " - XJ8 L"},
    {make: "JAG", code: "JAGXJR", display: " - XJR"},
    {make: "JAG", code: "JAGXJRS", display: " - XJR-S"},
    {make: "JAG", code: "JAGXJS", display: " - XJS"},
    {make: "JAG", code: "XK_SERIES", display: "XK Series (3)"},
    {make: "JAG", code: "XK", display: " - XK"},
    {make: "JAG", code: "JAGXK8", display: " - XK8"},
    {make: "JAG", code: "XKR", display: " - XKR"},
    {make: "JAG", code: "JAGOTH", display: "Other Jaguar Models"},
    
    // JEEP
    {make: "JEEP", code: "CHER", display: "Cherokee"},
    {make: "JEEP", code: "JEEPCJ", display: "CJ"},
    {make: "JEEP", code: "COMANC", display: "Comanche"},
    {make: "JEEP", code: "COMMANDER", display: "Commander"},
    {make: "JEEP", code: "COMPASS", display: "Compass"},
    {make: "JEEP", code: "JEEPGRAND", display: "Grand Cherokee"},
    {make: "JEEP", code: "GRWAG", display: "Grand Wagoneer"},
    {make: "JEEP", code: "LIBERTY", display: "Liberty"},
    {make: "JEEP", code: "PATRIOT", display: "Patriot"},
    {make: "JEEP", code: "JEEPPU", display: "Pickup"},
    {make: "JEEP", code: "JEEPRENEG", display: "Renegade"},
    {make: "JEEP", code: "SCRAMBLE", display: "Scrambler"},
    {make: "JEEP", code: "WAGONE", display: "Wagoneer"},
    {make: "JEEP", code: "WRANGLER", display: "Wrangler"},
    {make: "JEEP", code: "JEOTH", display: "Other Jeep Models"},
    
    // KIA
    {make: "KIA", code: "AMANTI", display: "Amanti"},
    {make: "KIA", code: "BORREGO", display: "Borrego"},
    {make: "KIA", code: "KIACADENZA", display: "Cadenza"},
    {make: "KIA", code: "FORTE", display: "Forte"},
    {make: "KIA", code: "FORTEKOUP", display: "Forte Koup"},
    {make: "KIA", code: "KIAK900", display: "K900"},
    {make: "KIA", code: "OPTIMA", display: "Optima"},
    {make: "KIA", code: "RIO", display: "Rio"},
    {make: "KIA", code: "RIO5", display: "Rio5"},
    {make: "KIA", code: "RONDO", display: "Rondo"},
    {make: "KIA", code: "SEDONA", display: "Sedona"},
    {make: "KIA", code: "SEPHIA", display: "Sephia"},
    {make: "KIA", code: "SORENTO", display: "Sorento"},
    {make: "KIA", code: "SOUL", display: "Soul"},
    {make: "KIA", code: "SPECTRA", display: "Spectra"},
    {make: "KIA", code: "SPECTRA5", display: "Spectra5"},
    {make: "KIA", code: "SPORTA", display: "Sportage"},
    {make: "KIA", code: "KIAOTH", display: "Other Kia Models"},
    
    // Lambo
    {make: "LAM", code: "AVENT", display: "Aventador"},
    {make: "LAM", code: "COUNT", display: "Countach"},
    {make: "LAM", code: "DIABLO", display: "Diablo"},
    {make: "LAM", code: "GALLARDO", display: "Gallardo"},
    {make: "LAM", code: "LAMHURACAN", display: "Huracan"},
    {make: "LAM", code: "JALPA", display: "Jalpa"},
    {make: "LAM", code: "LM002", display: "LM002"},
    {make: "LAM", code: "MURCIELAGO", display: "Murcielago"},
    {make: "LAM", code: "LAMOTH", display: "Other Lamborghini Models"},
    
    // Land Rover
    {make: "ROV", code: "DEFEND", display: "Defender"},
    {make: "ROV", code: "DISCOV", display: "Discovery"},
    {make: "ROV", code: "ROVDISCSPT", display: "Discovery Sport"},
    {make: "ROV", code: "FRELNDR", display: "Freelander"},
    {make: "ROV", code: "LR2", display: "LR2"},
    {make: "ROV", code: "LR3", display: "LR3"},
    {make: "ROV", code: "LR4", display: "LR4"},
    {make: "ROV", code: "RANGE", display: "Range Rover"},
    {make: "ROV", code: "EVOQUE", display: "Range Rover Evoque"},
    {make: "ROV", code: "RANGESPORT", display: "Range Rover Sport"},
    {make: "ROV", code: "ROVOTH", display: "Other Land Rover Models"},
    
    // Lexus
    {make: "LEXUS", code: "CT200H", display: "CT 200h"},
    {make: "LEXUS", code: "ES_MODELS", display: "ES Models (5)"},
    {make: "LEXUS", code: "ES250", display: " - ES 250"},
    {make: "LEXUS", code: "ES300", display: " - ES 300"},
    {make: "LEXUS", code: "ES300H", display: " - ES 300h"},
    {make: "LEXUS", code: "ES330", display: " - ES 330"},
    {make: "LEXUS", code: "ES350", display: " - ES 350"},
    {make: "LEXUS", code: "GS_MODELS", display: "GS Models (8)"},
    {make: "LEXUS", code: "LEXGS200T", display: " - GS 200t"},
    {make: "LEXUS", code: "GS300", display: " - GS 300"},
    {make: "LEXUS", code: "GS350", display: " - GS 350"},
    {make: "LEXUS", code: "GS400", display: " - GS 400"},
    {make: "LEXUS", code: "GS430", display: " - GS 430"},
    {make: "LEXUS", code: "GS450H", display: " - GS 450h"},
    {make: "LEXUS", code: "GS460", display: " - GS 460"},
    {make: "LEXUS", code: "LEXGSF", display: " - GS F"},
    {make: "LEXUS", code: "GX_MODELS", display: "GX Models (2)"},
    {make: "LEXUS", code: "GX460", display: " - GX 460"},
    {make: "LEXUS", code: "GX470", display: " - GX 470"},
    {make: "LEXUS", code: "HS250H", display: "HS 250h"},
    {make: "LEXUS", code: "IS_MODELS", display: "IS Models (7)"},
    {make: "LEXUS", code: "LEXIS200T", display: " - IS 200t"},
    {make: "LEXUS", code: "IS250", display: " - IS 250"},
    {make: "LEXUS", code: "IS250C", display: " - IS 250C"},
    {make: "LEXUS", code: "IS300", display: " - IS 300"},
    {make: "LEXUS", code: "IS350", display: " - IS 350"},
    {make: "LEXUS", code: "IS350C", display: " - IS 350C"},
    {make: "LEXUS", code: "ISF", display: " - IS F"},
    {make: "LEXUS", code: "LEXLFA", display: "LFA"},
    {make: "LEXUS", code: "LS_MODELS", display: "LS Models (4)"},
    {make: "LEXUS", code: "LS400", display: " - LS 400"},
    {make: "LEXUS", code: "LS430", display: " - LS 430"},
    {make: "LEXUS", code: "LS460", display: " - LS 460"},
    {make: "LEXUS", code: "LS600H", display: " - LS 600h"},
    {make: "LEXUS", code: "LX_MODELS", display: "LX Models (3)"},
    {make: "LEXUS", code: "LX450", display: " - LX 450"},
    {make: "LEXUS", code: "LX470", display: " - LX 470"},
    {make: "LEXUS", code: "LX570", display: " - LX 570"},
    {make: "LEXUS", code: "NX_MODELS", display: "NX Models (2)"},
    {make: "LEXUS", code: "LEXNX200T", display: " - NX 200t"},
    {make: "LEXUS", code: "LEXNX300H", display: " - NX 300h"},
    {make: "LEXUS", code: "RC_MODELS", display: "RC Models (3)"},
    {make: "LEXUS", code: "LEXRC200T", display: " - RC 200t"},
    {make: "LEXUS", code: "LEXRC350", display: " - RC 350"},
    {make: "LEXUS", code: "LEXRCF", display: " - RC F"},
    {make: "LEXUS", code: "RX_MODELS", display: "RX Models (5)"},
    {make: "LEXUS", code: "RX300", display: " - RX 300"},
    {make: "LEXUS", code: "RX330", display: " - RX 330"},
    {make: "LEXUS", code: "RX350", display: " - RX 350"},
    {make: "LEXUS", code: "RX400H", display: " - RX 400h"},
    {make: "LEXUS", code: "RX450H", display: " - RX 450h"},
    {make: "LEXUS", code: "SC_MODELS", display: "SC Models (3)"},
    {make: "LEXUS", code: "SC300", display: " - SC 300"},
    {make: "LEXUS", code: "SC400", display: " - SC 400"},
    {make: "LEXUS", code: "SC430", display: " - SC 430"},
    {make: "LEXUS", code: "LEXOTH", display: "Other Lexus Models"},
    
    // Lincoln
    {make: "LINC", code: "AVIATOR", display: "Aviator"},
    {make: "LINC", code: "BLKWOOD", display: "Blackwood"},
    {make: "LINC", code: "CONT", display: "Continental"},
    {make: "LINC", code: "LSLINCOLN", display: "LS"},
    {make: "LINC", code: "MARKLT", display: "Mark LT"},
    {make: "LINC", code: "MARK6", display: "Mark VI"},
    {make: "LINC", code: "MARK7", display: "Mark VII"},
    {make: "LINC", code: "MARK8", display: "Mark VIII"},
    {make: "LINC", code: "LINCMKC", display: "MKC"},
    {make: "LINC", code: "MKS", display: "MKS"},
    {make: "LINC", code: "MKT", display: "MKT"},
    {make: "LINC", code: "MKX", display: "MKX"},
    {make: "LINC", code: "MKZ", display: "MKZ"},
    {make: "LINC", code: "NAVIGA", display: "Navigator"},
    {make: "LINC", code: "NAVIGAL", display: "Navigator L"},
    {make: "LINC", code: "LINCTC", display: "Town Car"},
    {make: "LINC", code: "ZEPHYR", display: "Zephyr"},
    {make: "LINC", code: "LINOTH", display: "Other Lincoln Models"},
    
    // Lotus
    {make: "LOTUS", code: "ELAN", display: "Elan"},
    {make: "LOTUS", code: "LOTELISE", display: "Elise"},
    {make: "LOTUS", code: "ESPRIT", display: "Esprit"},
    {make: "LOTUS", code: "EVORA", display: "Evora"},
    {make: "LOTUS", code: "EXIGE", display: "Exige"},
    {make: "LOTUS", code: "LOTOTH", display: "Other Lotus Models"},
    
    // Maserati
    {make: "MAS", code: "430", display: "430"},
    {make: "MAS", code: "BITRBO", display: "Biturbo"},
    {make: "MAS", code: "COUPEMAS", display: "Coupe"},
    {make: "MAS", code: "GHIB", display: "Ghibli"},
    {make: "MAS", code: "GRANSPORT", display: "GranSport"},
    {make: "MAS", code: "GRANTURISM", display: "GranTurismo"},
    {make: "MAS", code: "QP", display: "Quattroporte"},
    {make: "MAS", code: "SPYDER", display: "Spyder"},
    {make: "MAS", code: "MASOTH", display: "Other Maserati Models"},
    
    // Maybach
    {make: "MAYBACH", code: "57MAYBACH", display: "57"},
    {make: "MAYBACH", code: "62MAYBACH", display: "62"},
    {make: "MAYBACH", code: "MAYOTH", display: "Other Maybach Models"},
    
    // Mazda
    {make: "MAZDA", code: "MAZDA323", display: "323"},
    {make: "MAZDA", code: "MAZDA626", display: "626"},
    {make: "MAZDA", code: "929", display: "929"},
    {make: "MAZDA", code: "B-SERIES", display: "B-Series Pickup"},
    {make: "MAZDA", code: "MAZCX3", display: "CX-3"},
    {make: "MAZDA", code: "CX-5", display: "CX-5"},
    {make: "MAZDA", code: "CX-7", display: "CX-7"},
    {make: "MAZDA", code: "CX-9", display: "CX-9"},
    {make: "MAZDA", code: "GLC", display: "GLC"},
    {make: "MAZDA", code: "MAZDA2", display: "MAZDA2"},
    {make: "MAZDA", code: "MAZDA3", display: "MAZDA3"},
    {make: "MAZDA", code: "MAZDA5", display: "MAZDA5"},
    {make: "MAZDA", code: "MAZDA6", display: "MAZDA6"},
    {make: "MAZDA", code: "MAZDASPD3", display: "MAZDASPEED3"},
    {make: "MAZDA", code: "MAZDASPD6", display: "MAZDASPEED6"},
    {make: "MAZDA", code: "MILL", display: "Millenia"},
    {make: "MAZDA", code: "MPV", display: "MPV"},
    {make: "MAZDA", code: "MIATA", display: "MX-5 Miata"},
    {make: "MAZDA", code: "MX3", display: "MX3"},
    {make: "MAZDA", code: "MX6", display: "MX6"},
    {make: "MAZDA", code: "NAVAJO", display: "Navajo"},
    {make: "MAZDA", code: "PROTE", display: "Protege"},
    {make: "MAZDA", code: "PROTE5", display: "Protege5"},
    {make: "MAZDA", code: "RX7", display: "RX-7"},
    {make: "MAZDA", code: "RX8", display: "RX-8"},
    {make: "MAZDA", code: "TRIBUTE", display: "Tribute"},
    {make: "MAZDA", code: "MAZOTH", display: "Other Mazda Models"},
    
    // McLaren
    {make: "MCLAREN", code: "MCL570S", display: "570S"},
    {make: "MCLAREN", code: "MCL650S", display: "650S"},
    {make: "MCLAREN", code: "MCL675LT", display: "675LT"},
    {make: "MCLAREN", code: "MP4", display: "MP4-12C"},
    {make: "MCLAREN", code: "MCLP1", display: "P1"},
    
    // Mercedes-Benz
    {make: "MB", code: "190D", display: "190D"},
    {make: "MB", code: "190E", display: "190E"},
    {make: "MB", code: "240D", display: "240D"},
    {make: "MB", code: "260E", display: "260E"},
    {make: "MB", code: "280CE", display: "280CE"},
    {make: "MB", code: "280E", display: "280E"},
    {make: "MB", code: "300CD", display: "300CD"},
    {make: "MB", code: "300CE", display: "300CE"},
    {make: "MB", code: "300D", display: "300D"},
    {make: "MB", code: "300E", display: "300E"},
    {make: "MB", code: "300SD", display: "300SD"},
    {make: "MB", code: "300SDL", display: "300SDL"},
    {make: "MB", code: "300SE", display: "300SE"},
    {make: "MB", code: "300SEL", display: "300SEL"},
    {make: "MB", code: "300SL", display: "300SL"},
    {make: "MB", code: "300TD", display: "300TD"},
    {make: "MB", code: "300TE", display: "300TE"},
    {make: "MB", code: "350SD", display: "350SD"},
    {make: "MB", code: "350SDL", display: "350SDL"},
    {make: "MB", code: "380SE", display: "380SE"},
    {make: "MB", code: "380SEC", display: "380SEC"},
    {make: "MB", code: "380SEL", display: "380SEL"},
    {make: "MB", code: "380SL", display: "380SL"},
    {make: "MB", code: "380SLC", display: "380SLC"},
    {make: "MB", code: "400E", display: "400E"},
    {make: "MB", code: "400SE", display: "400SE"},
    {make: "MB", code: "400SEL", display: "400SEL"},
    {make: "MB", code: "420SEL", display: "420SEL"},
    {make: "MB", code: "500E", display: "500E"},
    {make: "MB", code: "500SEC", display: "500SEC"},
    {make: "MB", code: "500SEL", display: "500SEL"},
    {make: "MB", code: "500SL", display: "500SL"},
    {make: "MB", code: "560SEC", display: "560SEC"},
    {make: "MB", code: "560SEL", display: "560SEL"},
    {make: "MB", code: "560SL", display: "560SL"},
    {make: "MB", code: "600SEC", display: "600SEC"},
    {make: "MB", code: "600SEL", display: "600SEL"},
    {make: "MB", code: "600SL", display: "600SL"},
    {make: "MB", code: "MBAMGGT", display: "AMG GT"},
    {make: "MB", code: "MBBCLASSED", display: "B-Class Electric Drive"},
    {make: "MB", code: "C_CLASS", display: "C-Class (15)"},
    {make: "MB", code: "C220", display: " - C220"},
    {make: "MB", code: "C230", display: " - C230"},
    {make: "MB", code: "C240", display: " - C240"},
    {make: "MB", code: "C250", display: " - C250"},
    {make: "MB", code: "C280", display: " - C280"},
    {make: "MB", code: "C300", display: " - C300"},
    {make: "MB", code: "C32AMG", display: " - C32 AMG"},
    {make: "MB", code: "C320", display: " - C320"},
    {make: "MB", code: "C350", display: " - C350"},
    {make: "MB", code: "C36AMG", display: " - C36 AMG"},
    {make: "MB", code: "MBC400", display: " - C400"},
    {make: "MB", code: "C43AMG", display: " - C43 AMG"},
    {make: "MB", code: "MBC450", display: " - C450"},
    {make: "MB", code: "C55AMG", display: " - C55 AMG"},
    {make: "MB", code: "C63AMG", display: " - C63 AMG"},
    {make: "MB", code: "CL_CLASS", display: "CL-Class (6)"},
    {make: "MB", code: "CL500", display: " - CL500"},
    {make: "MB", code: "CL55AMG", display: " - CL55 AMG"},
    {make: "MB", code: "CL550", display: " - CL550"},
    {make: "MB", code: "CL600", display: " - CL600"},
    {make: "MB", code: "CL63AMG", display: " - CL63 AMG"},
    {make: "MB", code: "CL65AMG", display: " - CL65 AMG"},
    {make: "MB", code: "CLA_CLASS", display: "CLA-Class (2)"},
    {make: "MB", code: "MBCLA250", display: " - CLA250"},
    {make: "MB", code: "MBCLA45AMG", display: " - CLA45 AMG"},
    {make: "MB", code: "CLK_CLASS", display: "CLK-Class (7)"},
    {make: "MB", code: "CLK320", display: " - CLK320"},
    {make: "MB", code: "CLK350", display: " - CLK350"},
    {make: "MB", code: "CLK430", display: " - CLK430"},
    {make: "MB", code: "CLK500", display: " - CLK500"},
    {make: "MB", code: "CLK55AMG", display: " - CLK55 AMG"},
    {make: "MB", code: "CLK550", display: " - CLK550"},
    {make: "MB", code: "CLK63AMG", display: " - CLK63 AMG"},
    {make: "MB", code: "CLS_CLASS", display: "CLS-Class (5)"},
    {make: "MB", code: "MBCLS400", display: " - CLS400"},
    {make: "MB", code: "CLS500", display: " - CLS500"},
    {make: "MB", code: "CLS55AMG", display: " - CLS55 AMG"},
    {make: "MB", code: "CLS550", display: " - CLS550"},
    {make: "MB", code: "CLS63AMG", display: " - CLS63 AMG"},
    {make: "MB", code: "E_CLASS", display: "E-Class (11)"},
    {make: "MB", code: "MBE250BLUE", display: " - E250"},
    {make: "MB", code: "E300", display: " - E300"},
    {make: "MB", code: "E320", display: " - E320"},
    {make: "MB", code: "E350", display: " - E350"},
    {make: "MB", code: "MBE400", display: " - E400"},
    {make: "MB", code: "E420", display: " - E420"},
    {make: "MB", code: "E430", display: " - E430"},
    {make: "MB", code: "E500", display: " - E500"},
    {make: "MB", code: "E55AMG", display: " - E55 AMG"},
    {make: "MB", code: "E550", display: " - E550"},
    {make: "MB", code: "E63AMG", display: " - E63 AMG"},
    {make: "MB", code: "G_CLASS", display: "G-Class (5)"},
    {make: "MB", code: "G500", display: " - G500"},
    {make: "MB", code: "G55AMG", display: " - G55 AMG"},
    {make: "MB", code: "G550", display: " - G550"},
    {make: "MB", code: "G63AMG", display: " - G63 AMG"},
    {make: "MB", code: "MBG65AMG", display: " - G65 AMG"},
    {make: "MB", code: "GL_CLASS", display: "GL-Class (5)"},
    {make: "MB", code: "GL320BLUE", display: " - GL320"},
    {make: "MB", code: "GL350BLUE", display: " - GL350"},
    {make: "MB", code: "GL450", display: " - GL450"},
    {make: "MB", code: "GL550", display: " - GL550"},
    {make: "MB", code: "GL63AMG", display: " - GL63 AMG"},
    {make: "MB", code: "GLA_CLASS", display: "GLA-Class (2)"},
    {make: "MB", code: "MBGLA250", display: " - GLA250"},
    {make: "MB", code: "MBGLA45AMG", display: " - GLA45 AMG"},
    {make: "MB", code: "MBGLC300", display: "GLC300"},
    {make: "MB", code: "GLE_CLASS", display: "GLE-Class (6)"},
    {make: "MB", code: "MBGLE300D", display: " - GLE300d"},
    {make: "MB", code: "MBGLE350", display: " - GLE350"},
    {make: "MB", code: "MBGLE400", display: " - GLE400"},
    {make: "MB", code: "MBGLE450", display: " - GLE450"},
    {make: "MB", code: "MBGLE550E", display: " - GLE550e"},
    {make: "MB", code: "MBGLE63AMG", display: " - GLE63 AMG"},
    {make: "MB", code: "GLK_CLASS", display: "GLK-Class (2)"},
    {make: "MB", code: "GLK250BLUE", display: " - GLK250"},
    {make: "MB", code: "GLK350", display: " - GLK350"},
    {make: "MB", code: "M_CLASS", display: "M-Class (10)"},
    {make: "MB", code: "MBML250BLU", display: " - ML250"},
    {make: "MB", code: "ML320", display: " - ML320"},
    {make: "MB", code: "ML350", display: " - ML350"},
    {make: "MB", code: "MBML400", display: " - ML400"},
    {make: "MB", code: "ML430", display: " - ML430"},
    {make: "MB", code: "ML450HY", display: " - ML450"},
    {make: "MB", code: "ML500", display: " - ML500"},
    {make: "MB", code: "ML55AMG", display: " - ML55 AMG"},
    {make: "MB", code: "ML550", display: " - ML550"},
    {make: "MB", code: "ML63AMG", display: " - ML63 AMG"},
    {make: "MB", code: "MBMETRIS", display: "Metris"},
    {make: "MB", code: "R_CLASS", display: "R-Class (4)"},
    {make: "MB", code: "R320BLUE", display: " - R320"},
    {make: "MB", code: "R350", display: " - R350"},
    {make: "MB", code: "R500", display: " - R500"},
    {make: "MB", code: "R63AMG", display: " - R63 AMG"},
    {make: "MB", code: "S_CLASS", display: "S-Class (12)"},
    {make: "MB", code: "MBMAYS600", display: " - Maybach S600"},
    {make: "MB", code: "S320", display: " - S320"},
    {make: "MB", code: "S350", display: " - S350"},
    {make: "MB", code: "S400HY", display: " - S400"},
    {make: "MB", code: "S420", display: " - S420"},
    {make: "MB", code: "S430", display: " - S430"},
    {make: "MB", code: "S500", display: " - S500"},
    {make: "MB", code: "S55AMG", display: " - S55 AMG"},
    {make: "MB", code: "S550", display: " - S550"},
    {make: "MB", code: "S600", display: " - S600"},
    {make: "MB", code: "S63AMG", display: " - S63 AMG"},
    {make: "MB", code: "S65AMG", display: " - S65 AMG"},
    {make: "MB", code: "SL_CLASS", display: "SL-Class (8)"},
    {make: "MB", code: "SL320", display: " - SL320"},
    {make: "MB", code: "MBSL400", display: " - SL400"},
    {make: "MB", code: "SL500", display: " - SL500"},
    {make: "MB", code: "SL55AMG", display: " - SL55 AMG"},
    {make: "MB", code: "SL550", display: " - SL550"},
    {make: "MB", code: "SL600", display: " - SL600"},
    {make: "MB", code: "SL63AMG", display: " - SL63 AMG"},
    {make: "MB", code: "SL65AMG", display: " - SL65 AMG"},
    {make: "MB", code: "SLK_CLASS", display: "SLK-Class (8)"},
    {make: "MB", code: "SLK230", display: " - SLK230"},
    {make: "MB", code: "SLK250", display: " - SLK250"},
    {make: "MB", code: "SLK280", display: " - SLK280"},
    {make: "MB", code: "SLK300", display: " - SLK300"},
    {make: "MB", code: "SLK32AMG", display: " - SLK32 AMG"},
    {make: "MB", code: "SLK320", display: " - SLK320"},
    {make: "MB", code: "SLK350", display: " - SLK350"},
    {make: "MB", code: "SLK55AMG", display: " - SLK55 AMG"},
    {make: "MB", code: "SLR", display: "SLR"},
    {make: "MB", code: "SLSAMG", display: "SLS AMG"},
    {make: "MB", code: "MBSPRINTER", display: "Sprinter"},
    {make: "MB", code: "MBOTH", display: "Other Mercedes-Benz Models"},
    
    // Mercury
    {make: "MERC", code: "CAPRI", display: "Capri"},
    {make: "MERC", code: "COUGAR", display: "Cougar"},
    {make: "MERC", code: "MERCGRAND", display: "Grand Marquis"},
    {make: "MERC", code: "LN7", display: "LN7"},
    {make: "MERC", code: "LYNX", display: "Lynx"},
    {make: "MERC", code: "MARAUDER", display: "Marauder"},
    {make: "MERC", code: "MARINER", display: "Mariner"},
    {make: "MERC", code: "MARQ", display: "Marquis"},
    {make: "MERC", code: "MILAN", display: "Milan"},
    {make: "MERC", code: "MONTEGO", display: "Montego"},
    {make: "MERC", code: "MONTEREY", display: "Monterey"},
    {make: "MERC", code: "MOUNTA", display: "Mountaineer"},
    {make: "MERC", code: "MYSTIQ", display: "Mystique"},
    {make: "MERC", code: "SABLE", display: "Sable"},
    {make: "MERC", code: "TOPAZ", display: "Topaz"},
    {make: "MERC", code: "TRACER", display: "Tracer"},
    {make: "MERC", code: "VILLA", display: "Villager"},
    {make: "MERC", code: "MERCZEP", display: "Zephyr"},
    {make: "MERC", code: "MEOTH", display: "Other Mercury Models"},
    
    // Mini
    {make: "MINI", code: "COOPER", display: "Cooper"},
    {make: "MINI", code: "COOPERCLUB", display: "Cooper Clubman"},
    {make: "MINI", code: "COUNTRYMAN", display: "Cooper Countryman"},
    {make: "MINI", code: "MINICOUPE", display: "Cooper Coupe"},
    {make: "MINI", code: "MINIPACE", display: "Cooper Paceman"},
    {make: "MINI", code: "COOPERROAD", display: "Cooper Roadster"},
    
    // Mitsubishi
    {make: "MIT", code: "3000GT", display: "3000GT"},
    {make: "MIT", code: "CORD", display: "Cordia"},
    {make: "MIT", code: "DIAMAN", display: "Diamante"},
    {make: "MIT", code: "ECLIP", display: "Eclipse"},
    {make: "MIT", code: "ENDEAVOR", display: "Endeavor"},
    {make: "MIT", code: "MITEXP", display: "Expo"},
    {make: "MIT", code: "GALANT", display: "Galant"},
    {make: "MIT", code: "MITI", display: "i"},
    {make: "MIT", code: "LANCERMITS", display: "Lancer"},
    {make: "MIT", code: "LANCEREVO", display: "Lancer Evolution"},
    {make: "MIT", code: "MITPU", display: "Mighty Max"},
    {make: "MIT", code: "MIRAGE", display: "Mirage"},
    {make: "MIT", code: "MONT", display: "Montero"},
    {make: "MIT", code: "MONTSPORT", display: "Montero Sport"},
    {make: "MIT", code: "OUTLANDER", display: "Outlander"},
    {make: "MIT", code: "OUTLANDSPT", display: "Outlander Sport"},
    {make: "MIT", code: "PRECIS", display: "Precis"},
    {make: "MIT", code: "RAIDERMITS", display: "Raider"},
    {make: "MIT", code: "SIGMA", display: "Sigma"},
    {make: "MIT", code: "MITSTAR", display: "Starion"},
    {make: "MIT", code: "TRED", display: "Tredia"},
    {make: "MIT", code: "MITVAN", display: "Van"},
    {make: "MIT", code: "MITOTH", display: "Other Mitsubishi Models"},
    
    // Nissan
    {make: "NISSAN", code: "NIS200SX", display: "200SX"},
    {make: "NISSAN", code: "240SX", display: "240SX"},
    {make: "NISSAN", code: "300ZXTURBO", display: "300ZX"},
    {make: "NISSAN", code: "350Z", display: "350Z"},
    {make: "NISSAN", code: "370Z", display: "370Z"},
    {make: "NISSAN", code: "ALTIMA", display: "Altima"},
    {make: "NISSAN", code: "PATHARMADA", display: "Armada"},
    {make: "NISSAN", code: "AXXESS", display: "Axxess"},
    {make: "NISSAN", code: "CUBE", display: "Cube"},
    {make: "NISSAN", code: "FRONTI", display: "Frontier"},
    {make: "NISSAN", code: "GT-R", display: "GT-R"},
    {make: "NISSAN", code: "JUKE", display: "Juke"},
    {make: "NISSAN", code: "LEAF", display: "Leaf"},
    {make: "NISSAN", code: "MAX", display: "Maxima"},
    {make: "NISSAN", code: "MURANO", display: "Murano"},
    {make: "NISSAN", code: "MURANOCROS", display: "Murano CrossCabriolet"},
    {make: "NISSAN", code: "NV", display: "NV"},
    {make: "NISSAN", code: "NISNV200", display: "NV200"},
    {make: "NISSAN", code: "NX", display: "NX"},
    {make: "NISSAN", code: "PATH", display: "Pathfinder"},
    {make: "NISSAN", code: "NISPU", display: "Pickup"},
    {make: "NISSAN", code: "PULSAR", display: "Pulsar"},
    {make: "NISSAN", code: "QUEST", display: "Quest"},
    {make: "NISSAN", code: "ROGUE", display: "Rogue"},
    {make: "NISSAN", code: "SENTRA", display: "Sentra"},
    {make: "NISSAN", code: "STANZA", display: "Stanza"},
    {make: "NISSAN", code: "TITAN", display: "Titan"},
    {make: "NISSAN", code: "NISVAN", display: "Van"},
    {make: "NISSAN", code: "VERSA", display: "Versa"},
    {make: "NISSAN", code: "NISVERSNOT", display: "Versa Note"},
    {make: "NISSAN", code: "XTERRA", display: "Xterra"},
    {make: "NISSAN", code: "NISSOTH", display: "Other Nissan Models"},
    
    // Oldsmobile
    {make: "OLDS", code: "88", display: "88"},
    {make: "OLDS", code: "ACHIEV", display: "Achieva"},
    {make: "OLDS", code: "ALERO", display: "Alero"},
    {make: "OLDS", code: "AURORA", display: "Aurora"},
    {make: "OLDS", code: "BRAV", display: "Bravada"},
    {make: "OLDS", code: "CUCR", display: "Custom Cruiser"},
    {make: "OLDS", code: "OLDCUS", display: "Cutlass"},
    {make: "OLDS", code: "OLDCALAIS", display: "Cutlass Calais"},
    {make: "OLDS", code: "CIERA", display: "Cutlass Ciera"},
    {make: "OLDS", code: "CSUPR", display: "Cutlass Supreme"},
    {make: "OLDS", code: "OLDSFIR", display: "Firenza"},
    {make: "OLDS", code: "INTRIG", display: "Intrigue"},
    {make: "OLDS", code: "98", display: "Ninety-Eight"},
    {make: "OLDS", code: "OMEG", display: "Omega"},
    {make: "OLDS", code: "REGEN", display: "Regency"},
    {make: "OLDS", code: "SILHO", display: "Silhouette"},
    {make: "OLDS", code: "TORO", display: "Toronado"},
    {make: "OLDS", code: "OLDOTH", display: "Other Oldsmobile Models"},
    
    // Plymouth
    {make: "PLYM", code: "ACC", display: "Acclaim"},
    {make: "PLYM", code: "ARROW", display: "Arrow"},
    {make: "PLYM", code: "BREEZE", display: "Breeze"},
    {make: "PLYM", code: "CARAVE", display: "Caravelle"},
    {make: "PLYM", code: "CHAMP", display: "Champ"},
    {make: "PLYM", code: "COLT", display: "Colt"},
    {make: "PLYM", code: "PLYMCONQ", display: "Conquest"},
    {make: "PLYM", code: "GRANFURY", display: "Gran Fury"},
    {make: "PLYM", code: "PLYMGRANV", display: "Grand Voyager"},
    {make: "PLYM", code: "HORI", display: "Horizon"},
    {make: "PLYM", code: "LASER", display: "Laser"},
    {make: "PLYM", code: "NEON", display: "Neon"},
    {make: "PLYM", code: "PROWLE", display: "Prowler"},
    {make: "PLYM", code: "RELI", display: "Reliant"},
    {make: "PLYM", code: "SAPPOROPLY", display: "Sapporo"},
    {make: "PLYM", code: "SCAMP", display: "Scamp"},
    {make: "PLYM", code: "SUNDAN", display: "Sundance"},
    {make: "PLYM", code: "TRAILDUST", display: "Trailduster"},
    {make: "PLYM", code: "TURISMO", display: "Turismo"},
    {make: "PLYM", code: "VOYA", display: "Voyager"},
    {make: "PLYM", code: "PLYOTH", display: "Other Plymouth Models"},
    
    // Pontiac
    {make: "PONT", code: "T-1000", display: "1000"},
    {make: "PONT", code: "6000", display: "6000"},
    {make: "PONT", code: "AZTEK", display: "Aztek"},
    {make: "PONT", code: "BON", display: "Bonneville"},
    {make: "PONT", code: "CATALINA", display: "Catalina"},
    {make: "PONT", code: "FIERO", display: "Fiero"},
    {make: "PONT", code: "FBIRD", display: "Firebird"},
    {make: "PONT", code: "G3", display: "G3"},
    {make: "PONT", code: "G5", display: "G5"},
    {make: "PONT", code: "G6", display: "G6"},
    {make: "PONT", code: "G8", display: "G8"},
    {make: "PONT", code: "GRNDAM", display: "Grand Am"},
    {make: "PONT", code: "GP", display: "Grand Prix"},
    {make: "PONT", code: "GTO", display: "GTO"},
    {make: "PONT", code: "J2000", display: "J2000"},
    {make: "PONT", code: "LEMANS", display: "Le Mans"},
    {make: "PONT", code: "MONTANA", display: "Montana"},
    {make: "PONT", code: "PARISI", display: "Parisienne"},
    {make: "PONT", code: "PHOENIX", display: "Phoenix"},
    {make: "PONT", code: "SAFARIPONT", display: "Safari"},
    {make: "PONT", code: "SOLSTICE", display: "Solstice"},
    {make: "PONT", code: "SUNBIR", display: "Sunbird"},
    {make: "PONT", code: "SUNFIR", display: "Sunfire"},
    {make: "PONT", code: "TORRENT", display: "Torrent"},
    {make: "PONT", code: "TS", display: "Trans Sport"},
    {make: "PONT", code: "VIBE", display: "Vibe"},
    {make: "PONT", code: "PONOTH", display: "Other Pontiac Models"},
    
    // Porsche
    {make: "POR", code: "911", display: "911"},
    {make: "POR", code: "POR918SPYD", display: "918 Spyder"},
    {make: "POR", code: "924", display: "924"},
    {make: "POR", code: "928", display: "928"},
    {make: "POR", code: "944", display: "944"},
    {make: "POR", code: "968", display: "968"},
    {make: "POR", code: "BOXSTE", display: "Boxster"},
    {make: "POR", code: "CARRERAGT", display: "Carrera GT"},
    {make: "POR", code: "CAYENNE", display: "Cayenne"},
    {make: "POR", code: "CAYMAN", display: "Cayman"},
    {make: "POR", code: "PORMACAN", display: "Macan"},
    {make: "POR", code: "PANAMERA", display: "Panamera"},
    {make: "POR", code: "POROTH", display: "Other Porsche Models"},
    
    // Ram
    {make: "RAM", code: "RM1500", display: "1500"},
    {make: "RAM", code: "RM2500", display: "2500"},
    {make: "RAM", code: "RM3500", display: "3500"},
    {make: "RAM", code: "RM4500", display: "4500"},
    {make: "RAM", code: "RM5500", display: "5500"},
    {make: "RAM", code: "RMCV", display: "C/V"},
    {make: "RAM", code: "RMPROMAST", display: "ProMaster"},
    {make: "RAM", code: "RMPROCITY", display: "ProMaster City"},
    
    // Rolls-Royce
    {make: "RR", code: "CAMAR", display: "Camargue"},
    {make: "RR", code: "CORN", display: "Corniche"},
    {make: "RR", code: "GHOST", display: "Ghost"},
    {make: "RR", code: "PARKWARD", display: "Park Ward"},
    {make: "RR", code: "PHANT", display: "Phantom"},
    {make: "RR", code: "DAWN", display: "Silver Dawn"},
    {make: "RR", code: "SILSERAPH", display: "Silver Seraph"},
    {make: "RR", code: "RRSPIR", display: "Silver Spirit"},
    {make: "RR", code: "SPUR", display: "Silver Spur"},
    {make: "RR", code: "WRAI", display: "Wraith"},
    {make: "RR", code: "RROTH", display: "Other Rolls-Royce Models"},
    
    // Saab
    {make: "SAAB", code: "9-2X", display: "9-2X"},
    {make: "SAAB", code: "9-3", display: "9-3"},
    {make: "SAAB", code: "9-4X", display: "9-4X"},
    {make: "SAAB", code: "9-5", display: "9-5"},
    {make: "SAAB", code: "97X", display: "9-7X"},
    {make: "SAAB", code: "900", display: "900"},
    {make: "SAAB", code: "9000", display: "9000"},
    {make: "SAAB", code: "SAOTH", display: "Other Saab Models"},
    
    // Saturn
    {make: "SATURN", code: "ASTRA", display: "Astra"},
    {make: "SATURN", code: "AURA", display: "Aura"},
    {make: "SATURN", code: "ION", display: "ION"},
    {make: "SATURN", code: "SATLSE", display: "L-Series"},
    {make: "SATURN", code: "OUTLOOK", display: "Outlook"},
    {make: "SATURN", code: "RELAY", display: "Relay"},
    {make: "SATURN", code: "SATSSE", display: "S-Series"},
    {make: "SATURN", code: "SKY", display: "Sky"},
    {make: "SATURN", code: "VUE", display: "Vue"},
    {make: "SATURN", code: "SATOTH", display: "Other Saturn Models"},
    
    // Scion
    {make: "SCION", code: "SCIFRS", display: "FR-S"},
    {make: "SCION", code: "SCIIA", display: "iA"},
    {make: "SCION", code: "SCIIM", display: "iM"},
    {make: "SCION", code: "IQ", display: "iQ"},
    {make: "SCION", code: "TC", display: "tC"},
    {make: "SCION", code: "XA", display: "xA"},
    {make: "SCION", code: "XB", display: "xB"},
    {make: "SCION", code: "XD", display: "xD"},
    
    // Smart
    {make: "SMART", code: "FORTWO", display: "fortwo"},
    {make: "SMART", code: "SMOTH", display: "Other smart Models"},
    
    // SRT
    {make: "SRT", code: "SRTVIPER", display: "Viper"},
    
    // Subaru
    {make: "SUB", code: "BAJA", display: "Baja"},
    {make: "SUB", code: "BRAT", display: "Brat"},
    {make: "SUB", code: "SUBBRZ", display: "BRZ"},
    {make: "SUB", code: "FOREST", display: "Forester"},
    {make: "SUB", code: "IMPREZ", display: "Impreza"},
    {make: "SUB", code: "IMPWRX", display: "Impreza WRX"},
    {make: "SUB", code: "JUSTY", display: "Justy"},
    {make: "SUB", code: "SUBL", display: "L Series"},
    {make: "SUB", code: "LEGACY", display: "Legacy"},
    {make: "SUB", code: "LOYALE", display: "Loyale"},
    {make: "SUB", code: "SUBOUTBK", display: "Outback"},
    {make: "SUB", code: "SVX", display: "SVX"},
    {make: "SUB", code: "B9TRIBECA", display: "Tribeca"},
    {make: "SUB", code: "SUBWRX", display: "WRX"},
    {make: "SUB", code: "XT", display: "XT"},
    {make: "SUB", code: "XVCRSSTREK", display: "XV Crosstrek"},
    {make: "SUB", code: "SUBOTH", display: "Other Subaru Models"},
    
    // Suzuki
    {make: "SUZUKI", code: "AERIO", display: "Aerio"},
    {make: "SUZUKI", code: "EQUATOR", display: "Equator"},
    {make: "SUZUKI", code: "ESTEEM", display: "Esteem"},
    {make: "SUZUKI", code: "FORENZA", display: "Forenza"},
    {make: "SUZUKI", code: "GRANDV", display: "Grand Vitara"},
    {make: "SUZUKI", code: "KIZASHI", display: "Kizashi"},
    {make: "SUZUKI", code: "RENO", display: "Reno"},
    {make: "SUZUKI", code: "SAMUR", display: "Samurai"},
    {make: "SUZUKI", code: "SIDE", display: "Sidekick"},
    {make: "SUZUKI", code: "SWIFT", display: "Swift"},
    {make: "SUZUKI", code: "SX4", display: "SX4"},
    {make: "SUZUKI", code: "VERONA", display: "Verona"},
    {make: "SUZUKI", code: "VITARA", display: "Vitara"},
    {make: "SUZUKI", code: "X90", display: "X-90"},
    {make: "SUZUKI", code: "XL7", display: "XL7"},
    {make: "SUZUKI", code: "SUZOTH", display: "Other Suzuki Models"},
    
    // Tesla
    {make: "TESLA", code: "TESMODS", display: "Model S"},
    {make: "TESLA", code: "TESMODX", display: "Model X"},
    {make: "TESLA", code: "ROADSTER", display: "Roadster"},
    
    // Toyota
    {make: "TOYOTA", code: "4RUN", display: "4Runner"},
    {make: "TOYOTA", code: "AVALON", display: "Avalon"},
    {make: "TOYOTA", code: "CAMRY", display: "Camry"},
    {make: "TOYOTA", code: "CELICA", display: "Celica"},
    {make: "TOYOTA", code: "COROL", display: "Corolla"},
    {make: "TOYOTA", code: "CORONA", display: "Corona"},
    {make: "TOYOTA", code: "CRESS", display: "Cressida"},
    {make: "TOYOTA", code: "ECHO", display: "Echo"},
    {make: "TOYOTA", code: "FJCRUIS", display: "FJ Cruiser"},
    {make: "TOYOTA", code: "HIGHLANDER", display: "Highlander"},
    {make: "TOYOTA", code: "LC", display: "Land Cruiser"},
    {make: "TOYOTA", code: "MATRIX", display: "Matrix"},
    {make: "TOYOTA", code: "TOYMIRAI", display: "Mirai"},
    {make: "TOYOTA", code: "MR2", display: "MR2"},
    {make: "TOYOTA", code: "MR2SPYDR", display: "MR2 Spyder"},
    {make: "TOYOTA", code: "PASEO", display: "Paseo"},
    {make: "TOYOTA", code: "PICKUP", display: "Pickup"},
    {make: "TOYOTA", code: "PREVIA", display: "Previa"},
    {make: "TOYOTA", code: "PRIUS", display: "Prius"},
    {make: "TOYOTA", code: "PRIUSC", display: "Prius C"},
    {make: "TOYOTA", code: "PRIUSV", display: "Prius V"},
    {make: "TOYOTA", code: "RAV4", display: "RAV4"},
    {make: "TOYOTA", code: "SEQUOIA", display: "Sequoia"},
    {make: "TOYOTA", code: "SIENNA", display: "Sienna"},
    {make: "TOYOTA", code: "SOLARA", display: "Solara"},
    {make: "TOYOTA", code: "STARLET", display: "Starlet"},
    {make: "TOYOTA", code: "SUPRA", display: "Supra"},
    {make: "TOYOTA", code: "T100", display: "T100"},
    {make: "TOYOTA", code: "TACOMA", display: "Tacoma"},
    {make: "TOYOTA", code: "TERCEL", display: "Tercel"},
    {make: "TOYOTA", code: "TUNDRA", display: "Tundra"},
    {make: "TOYOTA", code: "TOYVAN", display: "Van"},
    {make: "TOYOTA", code: "VENZA", display: "Venza"},
    {make: "TOYOTA", code: "YARIS", display: "Yaris"},
    {make: "TOYOTA", code: "TOYOTH", display: "Other Toyota Models"},
    
    // Volkswagen
    {make: "VOLKS", code: "BEETLE", display: "Beetle"},
    {make: "VOLKS", code: "VOLKSCAB", display: "Cabrio"},
    {make: "VOLKS", code: "CAB", display: "Cabriolet"},
    {make: "VOLKS", code: "CC", display: "CC"},
    {make: "VOLKS", code: "CORR", display: "Corrado"},
    {make: "VOLKS", code: "DASHER", display: "Dasher"},
    {make: "VOLKS", code: "VOLKSEGOLF", display: "e-Golf"},
    {make: "VOLKS", code: "EOS", display: "Eos"},
    {make: "VOLKS", code: "EUROVAN", display: "Eurovan"},
    {make: "VOLKS", code: "VOLKSFOX", display: "Fox"},
    {make: "VOLKS", code: "GOLFR", display: "Golf R"},
    {make: "VOLKS", code: "GTI", display: "GTI"},
    {make: "VOLKS", code: "GOLFANDRABBITMODELS", display: "Golf and Rabbit Models (2)"},
    {make: "VOLKS", code: "GOLF", display: " - Golf"},
    {make: "VOLKS", code: "RABBIT", display: " - Rabbit"},
    {make: "VOLKS", code: "JET", display: "Jetta"},
    {make: "VOLKS", code: "PASS", display: "Passat"},
    {make: "VOLKS", code: "PHAETON", display: "Phaeton"},
    {make: "VOLKS", code: "RABBITPU", display: "Pickup"},
    {make: "VOLKS", code: "QUAN", display: "Quantum"},
    {make: "VOLKS", code: "R32", display: "R32"},
    {make: "VOLKS", code: "ROUTAN", display: "Routan"},
    {make: "VOLKS", code: "SCIR", display: "Scirocco"},
    {make: "VOLKS", code: "TIGUAN", display: "Tiguan"},
    {make: "VOLKS", code: "TOUAREG", display: "Touareg"},
    {make: "VOLKS", code: "VANAG", display: "Vanagon"},
    {make: "VOLKS", code: "VWOTH", display: "Other Volkswagen Models"},
    
    // Volvo
    {make: "VOLVO", code: "240", display: "240"},
    {make: "VOLVO", code: "260", display: "260"},
    {make: "VOLVO", code: "740", display: "740"},
    {make: "VOLVO", code: "760", display: "760"},
    {make: "VOLVO", code: "780", display: "780"},
    {make: "VOLVO", code: "850", display: "850"},
    {make: "VOLVO", code: "940", display: "940"},
    {make: "VOLVO", code: "960", display: "960"},
    {make: "VOLVO", code: "C30", display: "C30"},
    {make: "VOLVO", code: "C70", display: "C70"},
    {make: "VOLVO", code: "S40", display: "S40"},
    {make: "VOLVO", code: "S60", display: "S60"},
    {make: "VOLVO", code: "S70", display: "S70"},
    {make: "VOLVO", code: "S80", display: "S80"},
    {make: "VOLVO", code: "S90", display: "S90"},
    {make: "VOLVO", code: "V40", display: "V40"},
    {make: "VOLVO", code: "V50", display: "V50"},
    {make: "VOLVO", code: "VOLVOV60", display: "V60"},
    {make: "VOLVO", code: "V70", display: "V70"},
    {make: "VOLVO", code: "V90", display: "V90"},
    {make: "VOLVO", code: "XC60", display: "XC60"},
    {make: "VOLVO", code: "XC", display: "XC70"},
    {make: "VOLVO", code: "XC90", display: "XC90"},
    {make: "VOLVO", code: "VOLOTH", display: "Other Volvo Models"}

    
];