var modelSelect = [
// Acura
{code: "ACUCL", display: "CL"},
{code: "ILX", display: "ILX"},
{code: "INTEG", display: "Integra"},
{code: "LEGEND", display: "Legend"},
{code: "MDX", display: "MDX"},
{code: "NSX", display: "NSX"},
{code: "RDX", display: "RDX"},
{code: "RL", display: "RL"},
{code: "RLX", display: "RLX"},
{code: "RSX", display: "RSX"},
{code: "SLX", display: "SLX"},
{code: "TL", display: "TL"},
{code: "ACUTLX", display: "TLX"},
{code: "TSX", display: "TSX"},
{code: "VIGOR", display: "Vigor"},
{code: "ZDX", display: "ZDX"},
{code: "ACUOTH", display: "Other Acura Models"},

// Alfa Romeo
{code: "ALFA164", display: "164"},
{code: "ALFA4C", display: "4C"},
{code: "ALFA8C", display: "8C Competizione"},
{code: "ALFAGT", display: "GTV-6"},
{code: "MIL", display: "Milano"},
{code: "SPID", display: "Spider"},
{code: "ALFAOTH", display: "Other Alfa Romeo Models"},

// AMC
{code: "AMCALLIAN", display: "Alliance"},
{code: "CON", display: "Concord"},
{code: "EAGLE", display: "Eagle"},
{code: "AMCENC", display: "Encore"},
{code: "AMCSPIRIT", display: "Spirit"},
{code: "AMCOTH", display: "Other AMC Models"},

// Aston Martin
{code: "DB7", display: "DB7"},
{code: "DB9", display: "DB9"},
{code: "DBS", display: "DBS"},
{code: "LAGONDA", display: "Lagonda"},
{code: "RAPIDE", display: "Rapide"},
{code: "ASTRAPIDES", display: "Rapide S"},
{code: "V12VANT", display: "V12 Vantage"},
{code: "VANTAGE", display: "V8 Vantage"},
{code: "VANQUISH", display: "Vanquish"},
{code: "VIRAGE", display: "Virage"},
{code: "ASTOTH", display: "Other Aston Martin Models"},

// Audi
{code: "AUDI100", display: "100"},
{code: "AUDI200", display: "200"},
{code: "4000", display: "4000"},
{code: "5000", display: "5000"},
{code: "80", display: "80"},
{code: "90", display: "90"},
{code: "A3", display: "A3"},
{code: "A4", display: "A4"},
{code: "A5", display: "A5"},
{code: "A6", display: "A6"},
{code: "A7", display: "A7"},
{code: "A8", display: "A8"},
{code: "ALLRDQUA", display: "allroad"},
{code: "AUDICABRI", display: "Cabriolet"},
{code: "AUDICOUPE", display: "Coupe"},
{code: "Q3", display: "Q3"},
{code: "Q5", display: "Q5"},
{code: "Q7", display: "Q7"},
{code: "QUATTR", display: "Quattro"},
{code: "R8", display: "R8"},
{code: "RS4", display: "RS 4"},
{code: "RS5", display: "RS 5"},
{code: "RS6", display: "RS 6"},
{code: "AUDIRS7", display: "RS 7"},
{code: "AUDS3", display: "S3"},
{code: "S4", display: "S4"},
{code: "S5", display: "S5"},
{code: "S6", display: "S6"},
{code: "S7", display: "S7"},
{code: "S8", display: "S8"},
{code: "AUDISQ5", display: "SQ5"},
{code: "TT", display: "TT"},
{code: "TTRS", display: "TT RS"},
{code: "TTS", display: "TTS"},
{code: "V8", display: "V8 Quattro"},
{code: "AUDOTH", display: "Other Audi Models"},

// Bentley
{code: "ARNAGE", display: "Arnage"},
{code: "AZURE", display: "Azure"},
{code: "BROOKLANDS", display: "Brooklands"},
{code: "BENCONT", display: "Continental"},
{code: "BENEIGHT", display: "Eight"},
{code: "BENFLYSPUR", display: "Flying Spur"},
{code: "BENMUL", display: "Mulsanne"},
{code: "BENTURBO", display: "Turbo R"},
{code: "BENOTH", display: "Other Bentley Models"},

// {code: "1SERIESM", display: "1 Series M"},
{code: "1_SERIES", display: "1 Series (3)"},
{code: "128I", display: " - 128i"},
{code: "135I", display: " - 135i"},
{code: "135IS", display: " - 135is"},
{code: "2_SERIES", display: "2 Series (4)"},
{code: "BMW228I", display: " - 228i"},
{code: "BMW228IXD", display: " - 228i xDrive"},
{code: "BMWM235I", display: " - M235i"},
{code: "BMWM235IXD", display: " - M235i xDrive"},
{code: "3_SERIES", display: "3 Series (36)"},
{code: "318I", display: " - 318i"},
{code: "318IS", display: " - 318iS"},
{code: "318TI", display: " - 318ti"},
{code: "320I", display: " - 320i"},
{code: "320IXD", display: " - 320i xDrive"},
{code: "323CI", display: " - 323ci"},
{code: "323I", display: " - 323i"},
{code: "323IS", display: " - 323is"},
{code: "BMW325", display: " - 325"},
{code: "325CI", display: " - 325Ci"},
{code: "325E", display: " - 325e"},
{code: "325ES", display: " - 325es"},
{code: "325I", display: " - 325i"},
{code: "325IX", display: " - 325iX"},
{code: "325IS", display: " - 325is"},
{code: "325XI", display: " - 325xi"},
{code: "328CI", display: " - 328Ci"},
{code: "BMW328D", display: " - 328d"},
{code: "BMW328DXD", display: " - 328d xDrive"},
{code: "328I", display: " - 328i"},
{code: "BMW328GTXD", display: " - 328i Gran Turismo xDrive"},
{code: "328IXD", display: " - 328i xDrive"},
{code: "328IS", display: " - 328iS"},
{code: "328XI", display: " - 328xi"},
{code: "330CI", display: " - 330Ci"},
{code: "330I", display: " - 330i"},
{code: "330XI", display: " - 330xi"},
{code: "335D", display: " - 335d"},
{code: "335I", display: " - 335i"},
{code: "BMW335GTXD", display: " - 335i Gran Turismo xDrive"},
{code: "335IXD", display: " - 335i xDrive"},
{code: "335IS", display: " - 335is"},
{code: "335XI", display: " - 335xi"},
{code: "BMW340I", display: " - 340i"},
{code: "BMW340IXD", display: " - 340i xDrive"},
{code: "ACTIVE3", display: " - ActiveHybrid 3"},
{code: "4_SERIES", display: "4 Series (8)"},
{code: "BMW428I", display: " - 428i"},
{code: "BMW428GC", display: " - 428i Gran Coupe"},
{code: "BMW428GCXD", display: " - 428i Gran Coupe xDrive"},
{code: "BMW428IXD", display: " - 428i xDrive"},
{code: "BMW435I", display: " - 435i"},
{code: "BMW435GC", display: " - 435i Gran Coupe"},
{code: "BMW435GCXD", display: " - 435i Gran Coupe xDrive"},
{code: "BMW435IXD", display: " - 435i xDrive"},
{code: "5_SERIES", display: "5 Series (24)"},
{code: "524TD", display: " - 524td"},
{code: "525I", display: " - 525i"},
{code: "525XI", display: " - 525xi"},
{code: "528E", display: " - 528e"},
{code: "528I", display: " - 528i"},
{code: "528IXD", display: " - 528i xDrive"},
{code: "528XI", display: " - 528xi"},
{code: "530I", display: " - 530i"},
{code: "530XI", display: " - 530xi"},
{code: "533I", display: " - 533i"},
{code: "BMW535D", display: " - 535d"},
{code: "BMW535DXD", display: " - 535d xDrive"},
{code: "535I", display: " - 535i"},
{code: "535IGT", display: " - 535i Gran Turismo"},
{code: "535IGTXD", display: " - 535i Gran Turismo xDrive"},
{code: "535IXD", display: " - 535i xDrive"},
{code: "535XI", display: " - 535xi"},
{code: "540I", display: " - 540i"},
{code: "545I", display: " - 545i"},
{code: "550I", display: " - 550i"},
{code: "550IGT", display: " - 550i Gran Turismo"},
{code: "550IGTXD", display: " - 550i Gran Turismo xDrive"},
{code: "550IXD", display: " - 550i xDrive"},
{code: "ACTIVE5", display: " - ActiveHybrid 5"},
{code: "6_SERIES", display: "6 Series (13)"},
{code: "633CSI", display: " - 633CSi"},
{code: "635CSI", display: " - 635CSi"},
{code: "640I", display: " - 640i"},
{code: "640IGC", display: " - 640i Gran Coupe"},
{code: "BMW640GCXD", display: " - 640i Gran Coupe xDrive"},
{code: "BMW640IXD", display: " - 640i xDrive"},
{code: "645CI", display: " - 645Ci"},
{code: "650I", display: " - 650i"},
{code: "650IGC", display: " - 650i Gran Coupe"},
{code: "650IGCXD", display: " - 650i Gran Coupe xDrive"},
{code: "650IXD", display: " - 650i xDrive"},
{code: "BMWB6XDGC", display: " - ALPINA B6 xDrive Gran Coupe"},
{code: "L6", display: " - L6"},
{code: "7_SERIES", display: "7 Series (21)"},
{code: "733I", display: " - 733i"},
{code: "735I", display: " - 735i"},
{code: "735IL", display: " - 735iL"},
{code: "BMW740LDXD", display: " - 740Ld xDrive"},
{code: "740LI", display: " - 740Li"},
{code: "740LIXD", display: " - 740Li xDrive"},
{code: "740I", display: " - 740i"},
{code: "740IL", display: " - 740iL"},
{code: "745LI", display: " - 745Li"},
{code: "745I", display: " - 745i"},
{code: "750LI", display: " - 750Li"},
{code: "750LIXD", display: " - 750Li xDrive"},
{code: "750I", display: " - 750i"},
{code: "750IXD", display: " - 750i xDrive"},
{code: "750IL", display: " - 750iL"},
{code: "760LI", display: " - 760Li"},
{code: "760I", display: " - 760i"},
{code: "ALPINAB7", display: " - ALPINA B7"},
{code: "ALPINAB7XD", display: " - ALPINA B7 xDrive"},
{code: "ACTIVE7", display: " - ActiveHybrid 7"},
{code: "L7", display: " - L7"},
{code: "8_SERIES", display: "8 Series (4)"},
{code: "840CI", display: " - 840Ci"},
{code: "850CSI", display: " - 850CSi"},
{code: "850CI", display: " - 850Ci"},
{code: "850I", display: " - 850i"},
{code: "ACTIVEX6", display: "ActiveHybrid X6"},
{code: "BMWI3", display: "i3"},
{code: "BMWI8", display: "i8"},
{code: "BMWMCOUPE", display: "M Coupe"},
{code: "BMWROAD", display: "M Roadster"},
{code: "M3", display: "M3"},
{code: "BMWM4", display: "M4"},
{code: "M5", display: "M5"},
{code: "M6", display: "M6"},
{code: "BMWM6GC", display: "M6 Gran Coupe"},
{code: "X1", display: "X1"},
{code: "X3", display: "X3"},
{code: "BMWX4", display: "X4"},
{code: "X5", display: "X5"},
{code: "X5M", display: "X5 M"},
{code: "X6", display: "X6"},
{code: "X6M", display: "X6 M"},
{code: "Z3", display: "Z3"},
{code: "Z4", display: "Z4"},
{code: "Z8", display: "Z8"},
{code: "BMWOTH", display: "Other BMW Models"},

// Buick
{code: "BUICASCADA", display: "Cascada"},
{code: "CENT", display: "Century"},
{code: "ELEC", display: "Electra"},
{code: "ENCLAVE", display: "Enclave"},
{code: "BUIENC", display: "Encore"},
{code: "LACROSSE", display: "LaCrosse"},
{code: "LESA", display: "Le Sabre"},
{code: "LUCERNE", display: "Lucerne"},
{code: "PARK", display: "Park Avenue"},
{code: "RAINIER", display: "Rainier"},
{code: "REATTA", display: "Reatta"},
{code: "REG", display: "Regal"},
{code: "RENDEZVOUS", display: "Rendezvous"},
{code: "RIV", display: "Riviera"},
{code: "BUICKROAD", display: "Roadmaster"},
{code: "SKYH", display: "Skyhawk"},
{code: "SKYL", display: "Skylark"},
{code: "SOMER", display: "Somerset"},
{code: "TERRAZA", display: "Terraza"},
{code: "BUVERANO", display: "Verano"},
{code: "BUOTH", display: "Other Buick Models"},

// Cadillac
{code: "ALLANT", display: "Allante"},
{code: "ATS", display: "ATS"},
{code: "BROUGH", display: "Brougham"},
{code: "CATERA", display: "Catera"},
{code: "CIMA", display: "Cimarron"},
{code: "CADCT6", display: "CT6"},
{code: "CTS", display: "CTS"},
{code: "DEV", display: "De Ville"},
{code: "DTS", display: "DTS"},
{code: "ELDO", display: "Eldorado"},
{code: "CADELR", display: "ELR"},
{code: "ESCALA", display: "Escalade"},
{code: "ESCALAESV", display: "Escalade ESV"},
{code: "EXT", display: "Escalade EXT"},
{code: "FLEE", display: "Fleetwood"},
{code: "SEV", display: "Seville"},
{code: "SRX", display: "SRX"},
{code: "STS", display: "STS"},
{code: "XLR", display: "XLR"},
{code: "XTS", display: "XTS"},
{code: "CADOTH", display: "Other Cadillac Models"},

// Chevy
{code: "ASTRO", display: "Astro"},
{code: "AVALNCH", display: "Avalanche"},
{code: "AVEO", display: "Aveo"},
{code: "AVEO5", display: "Aveo5"},
{code: "BERETT", display: "Beretta"},
{code: "BLAZER", display: "Blazer"},
{code: "CAM", display: "Camaro"},
{code: "CAP", display: "Caprice"},
{code: "CHECAPS", display: "Captiva Sport"},
{code: "CAV", display: "Cavalier"},
{code: "CELE", display: "Celebrity"},
{code: "CHEVETTE", display: "Chevette"},
{code: "CITATION", display: "Citation"},
{code: "CHECITYEXP", display: "City Express"},
{code: "COBALT", display: "Cobalt"},
{code: "COLORADO", display: "Colorado"},
{code: "CORSI", display: "Corsica"},
{code: "CORV", display: "Corvette"},
{code: "CRUZE", display: "Cruze"},
{code: "ELCAM", display: "El Camino"},
{code: "EQUINOX", display: "Equinox"},
{code: "CHEXP1500", display: "Express 1500"},
{code: "CHEXP2500", display: "Express 2500"},
{code: "CHEXP3500", display: "Express 3500"},
{code: "CHEXP4500", display: "Express 4500"},
{code: "CHEG10", display: "G10"},
{code: "CHEG20", display: "G20"},
{code: "CHEG30", display: "G30"},
{code: "HHR", display: "HHR"},
{code: "CHEVIMP", display: "Impala"},
{code: "KODC4500", display: "Kodiak C4500"},
{code: "LUMINA", display: "Lumina"},
{code: "LAPV", display: "Lumina APV"},
{code: "LUV", display: "LUV"},
{code: "MALI", display: "Malibu"},
{code: "CHVMETR", display: "Metro"},
{code: "CHEVMONT", display: "Monte Carlo"},
{code: "NOVA", display: "Nova"},
{code: "CHEVPRIZM", display: "Prizm"},
{code: "CHVST", display: "S10 Blazer"},
{code: "S10PICKUP", display: "S10 Pickup"},
{code: "CHEV150", display: "Silverado and other C/K1500"},
{code: "CHEVC25", display: "Silverado and other C/K2500"},
{code: "CH3500PU", display: "Silverado and other C/K3500"},
{code: "SONIC", display: "Sonic"},
{code: "SPARK", display: "Spark"},
{code: "CHEVSPEC", display: "Spectrum"},
{code: "CHSPRINT", display: "Sprint"},
{code: "CHEVSS", display: "SS"},
{code: "SSR", display: "SSR"},
{code: "CHEVSUB", display: "Suburban"},
{code: "TAHOE", display: "Tahoe"},
{code: "TRACKE", display: "Tracker"},
{code: "TRAILBLZ", display: "TrailBlazer"},
{code: "TRAILBZEXT", display: "TrailBlazer EXT"},
{code: "TRAVERSE", display: "Traverse"},
{code: "CHETRAX", display: "Trax"},
{code: "UPLANDER", display: "Uplander"},
{code: "VENTUR", display: "Venture"},
{code: "VOLT", display: "Volt"},
{code: "CHEOTH", display: "Other Chevrolet Models"},

// Chrysler
{code: "CHRYS200", display: "200"},
{code: "300", display: "300"},
{code: "CHRY300", display: "300M"},
{code: "ASPEN", display: "Aspen"},
{code: "CIRRUS", display: "Cirrus"},
{code: "CONC", display: "Concorde"},
{code: "CHRYCONQ", display: "Conquest"},
{code: "CORDOBA", display: "Cordoba"},
{code: "CROSSFIRE", display: "Crossfire"},
{code: "ECLASS", display: "E Class"},
{code: "FIFTH", display: "Fifth Avenue"},
{code: "CHRYGRANDV", display: "Grand Voyager"},
{code: "IMPE", display: "Imperial"},
{code: "INTREPID", display: "Intrepid"},
{code: "CHRYLAS", display: "Laser"},
{code: "LEBA", display: "LeBaron"},
{code: "CHRYLEBGTS", display: "LeBaron GTS"},
{code: "LHS", display: "LHS"},
{code: "NY", display: "New Yorker"},
{code: "NEWPORT", display: "Newport"},
{code: "PACIFICA", display: "Pacifica"},
{code: "CHPROWLE", display: "Prowler"},
{code: "PTCRUIS", display: "PT Cruiser"},
{code: "CHRYSEB", display: "Sebring"},
{code: "CHRYTC", display: "TC by Maserati"},
{code: "TANDC", display: "Town & Country"},
{code: "VOYAGER", display: "Voyager"},
{code: "CHOTH", display: "Other Chrysler Models"},

// Daewoo
{code: "LANOS", display: "Lanos"},
{code: "LEGANZA", display: "Leganza"},
{code: "NUBIRA", display: "Nubira"},
{code: "DAEOTH", display: "Other Daewoo Models"},

// Datsun
{code: "DAT200SX", display: "200SX"},
{code: "DAT210", display: "210"},
{code: "280Z", display: "280ZX"},
{code: "300ZX", display: "300ZX"},
{code: "310", display: "310"},
{code: "510", display: "510"},
{code: "720", display: "720"},
{code: "810", display: "810"},
{code: "DATMAX", display: "Maxima"},
{code: "DATPU", display: "Pickup"},
{code: "PUL", display: "Pulsar"},
{code: "DATSENT", display: "Sentra"},
{code: "STAN", display: "Stanza"},
{code: "DATOTH", display: "Other Datsun Models"},

// DeLorean
{code: "DMC12", display: "DMC-12"},

// Dodge
{code: "400", display: "400"},
{code: "DOD600", display: "600"},
{code: "ARI", display: "Aries"},
{code: "AVENGR", display: "Avenger"},
{code: "B150", display: "B150"},
{code: "B1500", display: "B1500"},
{code: "B250", display: "B250"},
{code: "B2500", display: "B2500"},
{code: "B350", display: "B350"},
{code: "B3500", display: "B3500"},
{code: "CALIBER", display: "Caliber"},
{code: "DODCARA", display: "Caravan"},
{code: "CHALLENGER", display: "Challenger"},
{code: "DODCHAR", display: "Charger"},
{code: "DODCOLT", display: "Colt"},
{code: "DODCONQ", display: "Conquest"},
{code: "DODDW", display: "D/W Truck"},
{code: "DAKOTA", display: "Dakota"},
{code: "DODDART", display: "Dart"},
{code: "DAY", display: "Daytona"},
{code: "DIPLOMA", display: "Diplomat"},
{code: "DURANG", display: "Durango"},
{code: "DODDYNA", display: "Dynasty"},
{code: "GRANDCARAV", display: "Grand Caravan"},
{code: "INTRE", display: "Intrepid"},
{code: "JOURNEY", display: "Journey"},
{code: "LANCERDODG", display: "Lancer"},
{code: "MAGNUM", display: "Magnum"},
{code: "MIRADA", display: "Mirada"},
{code: "MONACO", display: "Monaco"},
{code: "DODNEON", display: "Neon"},
{code: "NITRO", display: "Nitro"},
{code: "OMNI", display: "Omni"},
{code: "RAIDER", display: "Raider"},
{code: "RAM1504WD", display: "Ram 1500 Truck"},
{code: "RAM25002WD", display: "Ram 2500 Truck"},
{code: "RAM3502WD", display: "Ram 3500 Truck"},
{code: "RAM4500", display: "Ram 4500 Truck"},
{code: "DODD50", display: "Ram 50 Truck"},
{code: "RAM5500", display: "Ram 5500 Truck"},
{code: "RAMSRT10", display: "Ram SRT-10"},
{code: "RAMCGR", display: "Ramcharger"},
{code: "RAMPAGE", display: "Rampage"},
{code: "DODSHAD", display: "Shadow"},
{code: "DODSPIR", display: "Spirit"},
{code: "SPRINTER", display: "Sprinter"},
{code: "SRT4", display: "SRT-4"},
{code: "STREGIS", display: "St. Regis"},
{code: "STEAL", display: "Stealth"},
{code: "STRATU", display: "Stratus"},
{code: "VIPER", display: "Viper"},
{code: "DOOTH", display: "Other Dodge Models"},

// Eagle
{code: "EAGLEMED", display: "Medallion"},
{code: "EAGLEPREM", display: "Premier"},
{code: "SUMMIT", display: "Summit"},
{code: "TALON", display: "Talon"},
{code: "VISION", display: "Vision"},
{code: "EAGOTH", display: "Other Eagle Models"},

// Ferrari
{code: "308", display: "308"},
{code: "328", display: "328"},
{code: "348", display: "348"},
{code: "360", display: "360"},
{code: "456GT", display: "456 GT"},
{code: "456MGT", display: "456M GT"},
{code: "458ITALIA", display: "458 Italia"},
{code: "512M", display: "512M"},
{code: "512TR", display: "512TR"},
{code: "550M", display: "550 Maranello"},
{code: "575M", display: "575M Maranello"},
{code: "599GTB", display: "599 GTB Fiorano"},
{code: "599GTO", display: "599 GTO"},
{code: "612SCAGLIE", display: "612 Scaglietti"},
{code: "FERCALIF", display: "California"},
{code: "ENZO", display: "Enzo"},
{code: "FERF12BERL", display: "F12 Berlinetta"},
{code: "F355", display: "F355"},
{code: "F40", display: "F40"},
{code: "F430", display: "F430"},
{code: "F50", display: "F50"},
{code: "FERFF", display: "FF"},
{code: "MOND", display: "Mondial"},
{code: "TEST", display: "Testarossa"},
{code: "FEROTH", display: "Other Ferrari Models"},

// FIAT
{code: "2000", display: "2000 Spider"},
{code: "FIAT500", display: "500"},
{code: "FIAT500L", display: "500L"},
{code: "FIAT500X", display: "500X"},
{code: "BERTON", display: "Bertone X1/9"},
{code: "BRAVA", display: "Brava"},
{code: "PININ", display: "Pininfarina Spider"},
{code: "STRADA", display: "Strada"},
{code: "FIATX19", display: "X1/9"},
{code: "FIAOTH", display: "Other Fiat Models"},

// Fisker
{code: "KARMA", display: "Karma"},

// Ford
{code: "AERO", display: "Aerostar"},
{code: "ASPIRE", display: "Aspire"},
{code: "BRON", display: "Bronco"},
{code: "B2", display: "Bronco II"},
{code: "FOCMAX", display: "C-MAX"},
{code: "CONTOUR", display: "Contour"},
{code: "COURIER", display: "Courier"},
{code: "CROWNVIC", display: "Crown Victoria"},
{code: "E100ECON", display: "E-100"},
{code: "E150ECON", display: "E-150 and Econoline 150"},
{code: "E250ECON", display: "E-250 and Econoline 250"},
{code: "E350ECON", display: "E-350 and Econoline 350"},
{code: "EDGE", display: "Edge"},
{code: "ESCAPE", display: "Escape"},
{code: "ESCO", display: "Escort"},
{code: "EXCURSION", display: "Excursion"},
{code: "EXP", display: "EXP"},
{code: "EXPEDI", display: "Expedition"},
{code: "EXPEDIEL", display: "Expedition EL"},
{code: "EXPLOR", display: "Explorer"},
{code: "SPORTTRAC", display: "Explorer Sport Trac"},
{code: "F100", display: "F100"},
{code: "F150PICKUP", display: "F150"},
{code: "F250", display: "F250"},
{code: "F350", display: "F350"},
{code: "F450", display: "F450"},
{code: "FAIRM", display: "Fairmont"},
{code: "FESTIV", display: "Festiva"},
{code: "FIESTA", display: "Fiesta"},
{code: "FIVEHUNDRE", display: "Five Hundred"},
{code: "FLEX", display: "Flex"},
{code: "FOCUS", display: "Focus"},
{code: "FREESTAR", display: "Freestar"},
{code: "FREESTYLE", display: "Freestyle"},
{code: "FUSION", display: "Fusion"},
{code: "GRANADA", display: "Granada"},
{code: "GT", display: "GT"},
{code: "LTD", display: "LTD"},
{code: "MUST", display: "Mustang"},
{code: "PROBE", display: "Probe"},
{code: "RANGER", display: "Ranger"},
{code: "TAURUS", display: "Taurus"},
{code: "TAURUSX", display: "Taurus X"},
{code: "TEMPO", display: "Tempo"},
{code: "TBIRD", display: "Thunderbird"},
{code: "FORDTRN150", display: "Transit 150"},
{code: "FORDTRN250", display: "Transit 250"},
{code: "FORDTRN350", display: "Transit 350"},
{code: "TRANSCONN", display: "Transit Connect"},
{code: "WINDST", display: "Windstar"},
{code: "FORDZX2", display: "ZX2 Escort"},
{code: "FOOTH", display: "Other Ford Models"},

// Freightliner
{code: "FRESPRINT", display: "Sprinter"},

// GEO
{code: "GEOMETRO", display: "Metro"},
{code: "GEOPRIZM", display: "Prizm"},
{code: "SPECT", display: "Spectrum"},
{code: "STORM", display: "Storm"},
{code: "GEOTRACK", display: "Tracker"},
{code: "GEOOTH", display: "Other Geo Models"},

// GMC
{code: "ACADIA", display: "Acadia"},
{code: "CABALLERO", display: "Caballero"},
{code: "CANYON", display: "Canyon"},
{code: "ENVOY", display: "Envoy"},
{code: "ENVOYXL", display: "Envoy XL"},
{code: "ENVOYXUV", display: "Envoy XUV"},
{code: "G1500", display: "G1500"},
{code: "G2500", display: "G2500"},
{code: "G3500", display: "G3500"},
{code: "JIM", display: "Jimmy"},
{code: "GMCS15", display: "S15 Jimmy"},
{code: "S15", display: "S15 Pickup"},
{code: "SAFARIGMC", display: "Safari"},
{code: "GMCSAVANA", display: "Savana 1500"},
{code: "GMCSAV2500", display: "Savana 2500"},
{code: "GMCSAV3500", display: "Savana 3500"},
{code: "GMCSAV4500", display: "Savana 4500"},
{code: "15SIPU4WD", display: "Sierra C/K1500"},
{code: "GMCC25PU", display: "Sierra C/K2500"},
{code: "GMC3500PU", display: "Sierra C/K3500"},
{code: "SONOMA", display: "Sonoma"},
{code: "SUB", display: "Suburban"},
{code: "GMCSYCLON", display: "Syclone"},
{code: "TERRAIN", display: "Terrain"},
{code: "TOPC4500", display: "TopKick C4500"},
{code: "TYPH", display: "Typhoon"},
{code: "YUKON", display: "Yukon"},
{code: "YUKONXL", display: "Yukon XL"},
{code: "GMCOTH", display: "Other GMC Models"},

// Honda
{code: "ACCORD", display: "Accord"},
{code: "CIVIC", display: "Civic"},
{code: "CRV", display: "CR-V"},
{code: "CRZ", display: "CR-Z"},
{code: "CRX", display: "CRX"},
{code: "CROSSTOUR_MODELS", display: "Crosstour Models (2)"},
{code: "CROSSTOUR", display: " - Accord Crosstour"},
{code: "HONCROSS", display: " - Crosstour"},
{code: "HONDELSOL", display: "Del Sol"},
{code: "ELEMENT", display: "Element"},
{code: "FIT", display: "Fit"},
{code: "HONHRV", display: "HR-V"},
{code: "INSIGHT", display: "Insight"},
{code: "ODYSSEY", display: "Odyssey"},
{code: "PASSPO", display: "Passport"},
{code: "PILOT", display: "Pilot"},
{code: "PRE", display: "Prelude"},
{code: "RIDGELINE", display: "Ridgeline"},
{code: "S2000", display: "S2000"},
{code: "HONOTH", display: "Other Honda Models"}




];